package mr_tooth.agenda;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import mr_tooth.utilitarios.*;
/**
 *
 * @author Pedro
 */
public class AlteraConsulta extends javax.swing.JFrame {
    ConectaBanco con_agenda;
    /** Creates new form AgendarConsulta */
    public AlteraConsulta(String cod, String hora, String paci, String dent, String obs) {
        initComponents();
        //Inicia a classe ConectaBanco
        con_agenda = new ConectaBanco();
        con_agenda.OpenDB();

        //Inseri nos campos de texto as informações
        txtCodigo.setText(cod);
        //cbData.setSelectedItem(data);
        txtHora.setText(hora);
        txtPaciente.setText(paci);
        txtDentista.setText(dent);
        txtObs.setText(obs);
        //cbTratamento.setSelectedItem(trat);
        //cbFaltou.setSelectedItem(falt);

        //Carrega os dados do banco nos Combox        
        this.CarregarCbTratamento();
    }    

    public void CarregarCbTratamento(){
        //Adiciona os tratamentos cadastrados no cbTratamento
        con_agenda.QuerySQL("SELECT cod_tratamento,nome_tra FROM tratamentos");
        try{
            while(con_agenda.rs.next()){
                cbTratamento.addItem(con_agenda.rs.getString("nome_tra"));
            }
        }
        catch(Exception erroTratamento){
            JOptionPane.showMessageDialog(null,"Erro ao carregar os tratamentos cadastrados !", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDtConsulta = new javax.swing.JLabel();
        cbData = new CalendarComboBox(true);
        lbHrConsulta = new javax.swing.JLabel();
        txtHora = new javax.swing.JFormattedTextField();
        lblPaciente = new javax.swing.JLabel();
        lblDentista = new javax.swing.JLabel();
        lblObs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        lblTratamento = new javax.swing.JLabel();
        cbTratamento = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblFaltou = new javax.swing.JLabel();
        cbFaltou = new javax.swing.JComboBox();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPaciente = new javax.swing.JTextField();
        txtDentista = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendar Consulta");

        lblDtConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12));
        lblDtConsulta.setText("Data da Consulta :");

        cbData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbDataFocusLost(evt);
            }
        });

        lbHrConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12));
        lbHrConsulta.setText("Hora da Consulta :");

        txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        lblPaciente.setText("Nome do Paciente :");

        lblDentista.setText("Nome do Dentista :");

        lblObs.setText("Observação :");

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        lblTratamento.setText("Tratamento :");

        cbTratamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o tratamento que será realizado" }));
        cbTratamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbTratamentoFocusLost(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Calendar Stop.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Calendar Confirmed.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblFaltou.setText("Faltou :");

        cbFaltou.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Nao" }));
        cbFaltou.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbFaltouFocusLost(evt);
            }
        });

        lblCodigo.setText("Código Consulta :");

        txtCodigo.setEditable(false);

        txtPaciente.setEditable(false);

        txtDentista.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFaltou)
                            .addComponent(lblTratamento))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTratamento, 0, 446, Short.MAX_VALUE)
                            .addComponent(cbFaltou, 0, 446, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObs)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblDentista)
                                .addGap(18, 18, 18)
                                .addComponent(txtDentista))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblPaciente)
                                .addGap(18, 18, 18)
                                .addComponent(txtPaciente))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDtConsulta)
                                    .addComponent(lblCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbData, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(lbHrConsulta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtCodigo))))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtConsulta)
                    .addComponent(lbHrConsulta)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaciente)
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDentista)
                    .addComponent(txtDentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObs))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTratamento)
                    .addComponent(cbTratamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaltou)
                    .addComponent(cbFaltou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addGap(23, 23, 23))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-627)/2, (screenSize.height-523)/2, 627, 523);
    }// </editor-fold>//GEN-END:initComponents

    private void cbTratamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbTratamentoFocusLost
       
    }//GEN-LAST:event_cbTratamentoFocusLost

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
               
        try{            
            String cod = txtCodigo.getText();
            String pac  = txtPaciente.getText();
            String dent = txtDentista.getText();
            String hora = txtHora.getText();
            String obs  = txtObs.getText();

            //Altera os dados no banco
            String AgendaUpdate = "UPDATE agenda SET data_agen = '"+((CalendarComboBox) cbData).getText()+"', hora_agen = '"+hora+"', nome_pac = '"+pac+"'," +
                    "nome_dent = '"+dent+"', observacao_agen = '"+obs+"', nome_tra = '"+cbTratamento.getSelectedItem()+"', faltou_agen = '"+cbFaltou.getSelectedItem()+"' WHERE cod_agenda = "+cod;
            con_agenda.stmt.executeUpdate(AgendaUpdate);
            JOptionPane.showMessageDialog(null,"Consulta alterada com sucesso!","Cadastrado!", JOptionPane.INFORMATION_MESSAGE);            
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível alterar a consulta!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cbDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbDataFocusLost
      
    }//GEN-LAST:event_cbDataFocusLost

    private void cbFaltouFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbFaltouFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFaltouFocusLost

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbData;
    private javax.swing.JComboBox cbFaltou;
    private javax.swing.JComboBox cbTratamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHrConsulta;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDentista;
    private javax.swing.JLabel lblDtConsulta;
    private javax.swing.JLabel lblFaltou;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblTratamento;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDentista;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables

}
