package mr_tooth.agenda;
import javax.swing.JOptionPane;
import mr_tooth.utilitarios.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pedro
 */
public class VerificaConsulta extends javax.swing.JFrame {
    ConectaBanco con_agen;
    /** Creates new form VerificaConsulta */
    public VerificaConsulta() {
      initComponents();
      con_agen = new ConectaBanco();
      con_agen.OpenDB();

      //Mostrando as consulta agendadas para hoje
      //con_agen.QuerySQL("SELECT * FROM agenda WHERE data_agen = '"+((CalendarComboBox) cbData).getText()+"'");
      
      //Mostrado todas as consultas agendadas
      con_agen.QuerySQL("SELECT * FROM agenda");
      this.PreencherJtable();
    }

    public void PreencherJtable(){
        DefaultTableModel Modelo = (DefaultTableModel)jTableConsultas.getModel();
        Modelo.setNumRows(0);

        try{
            while(con_agen.rs.next()){
                Modelo.addRow(new Object [] {
                    con_agen.rs.getString("cod_agenda"),
                    con_agen.rs.getString("data_agen"),
                    con_agen.rs.getString("hora_agen"),
                    con_agen.rs.getString("nome_pac"),
                    con_agen.rs.getString("nome_dent"),
                    con_agen.rs.getString("observacao_agen"),
                    con_agen.rs.getString("nome_tra"),
                    con_agen.rs.getString("faltou_agen"),
                });
            }
        } 
        catch(Exception erroTable){
            JOptionPane.showMessageDialog(null,"Erro ao carregar consultas agendadas","ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTableConsultas = new javax.swing.JTable();
        lblDtConsulta = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        cbData = new CalendarComboBox(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agenda");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("framePacientes"); // NOI18N

        jTableConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Data", "Hora", "Paciente ", "Dentista", "Observação", "Tratamento", "Faltou"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTableConsultas);
        jTableConsultas.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTableConsultas.getColumnModel().getColumn(1).setPreferredWidth(350);
        jTableConsultas.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableConsultas.getColumnModel().getColumn(3).setPreferredWidth(120);

        lblDtConsulta.setFont(new java.awt.Font("Segoe UI", 1, 12));
        lblDtConsulta.setText("Data da Consulta :");

        btnVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Calendar Search.png"))); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Calendar Add.png"))); // NOI18N
        btnAdicionar.setText("Agendar ");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Calendar Edit 2.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Calendar Delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDtConsulta)
                        .addGap(18, 18, 18)
                        .addComponent(cbData, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtConsulta)
                    .addComponent(btnVerificar)
                    .addComponent(cbData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addGap(41, 41, 41))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-901)/2, (screenSize.height-597)/2, 901, 597);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        new AgendaConsulta().setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        con_agen.QuerySQL("SELECT * FROM agenda WHERE data_agen = '"+((CalendarComboBox) cbData).getText()+"'");
        this.PreencherJtable();
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int LinhaSelecionada = this.jTableConsultas.getSelectedRow();
        String CodigoConsulta = this.jTableConsultas.getValueAt(LinhaSelecionada, 0).toString();

        try{
            //Busca no banco de dados o código do paciente selecionado para ser excluido
            String ConsultaSelecionado = "SELECT * FROM agenda WHERE cod_agenda = '"+CodigoConsulta+"'";
            con_agen.QuerySQL(ConsultaSelecionado);
            con_agen.rs.next();

            //Mensagem de confirmação
            String MsgConfirmacao = "Deseja realmente cancelar a consulta do paciente: \n "+con_agen.rs.getString("nome_pac")+" ?";
            int OpcaoEscolhida = JOptionPane.showConfirmDialog(null, MsgConfirmacao, "Excluir", JOptionPane.YES_NO_OPTION);

            if(OpcaoEscolhida == JOptionPane.YES_OPTION){
                //Excluindo a consulta agendada após a confirmação positiva
                String ExcluirConsulta = "DELETE FROM agenda WHERE cod_agenda = "+CodigoConsulta;
                int ExcluirSucesso  = con_agen.stmt.executeUpdate(ExcluirConsulta);

                if(ExcluirSucesso == 1){
                    JOptionPane.showMessageDialog(null,"Consulta cancelada com sucesso!","Excluir!", JOptionPane.INFORMATION_MESSAGE);
                    //Atualiza jTable
                    PreencherJtable();
                }
                else{                    
                    //Atualiza jTable
                    PreencherJtable();
                    return;
                }
            }
            else{
                //Atualiza jTable
                PreencherJtable();
                return;
            }
        }
        catch(Exception erroSQL){
             JOptionPane.showMessageDialog(null,"Erro ao excluir", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int LinhaSelecionada = this.jTableConsultas.getSelectedRow();
        String cod   = this.jTableConsultas.getValueAt(LinhaSelecionada, 0).toString();
        //String data  = this.jTableConsultas.getValueAt(LinhaSelecionada, 1).toString();
        String hora  = this.jTableConsultas.getValueAt(LinhaSelecionada, 2).toString();
        String paci  = this.jTableConsultas.getValueAt(LinhaSelecionada, 3).toString();
        String dent  = this.jTableConsultas.getValueAt(LinhaSelecionada, 4).toString();
        String obs   = this.jTableConsultas.getValueAt(LinhaSelecionada, 5).toString();
        //String trat  = this.jTableConsultas.getValueAt(LinhaSelecionada, 6).toString();
        //String falt  = this.jTableConsultas.getValueAt(LinhaSelecionada, 7).toString();

        con_agen.CloseDB();

        new AlteraConsulta(cod, hora, paci, dent, obs).setVisible(true);
    }//GEN-LAST:event_btnAlterarActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
         public void run(){
                new VerificaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JComboBox cbData;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableConsultas;
    private javax.swing.JLabel lblDtConsulta;
    // End of variables declaration//GEN-END:variables

}
