package mr_tooth.principal;
import mr_tooth.utilitarios.ConectaBanco;
import mr_tooth.utilitarios.Constantes;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.sql.*;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mr_tooth.utilitarios.Parametros;
/**
 *
 * @author Pedro
 */
public class Login extends javax.swing.JFrame {
        ConectaBanco con_login;
        Parametros  p=new Parametros();
       /** Creates new form JF_Login */
    public Login() {
       //Look And Feel     
        try {            
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");            
            SwingUtilities.updateComponentTreeUI(this);
        }
        catch(Exception erro) {
            JOptionPane.showMessageDialog(null,"Erro ao caregar o tema : "+erro);
        }
        initComponents();
        con_login = new ConectaBanco();
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFundo = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName("frameLogin"); // NOI18N
        setResizable(false);
        ImageIcon bimg=   new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/imagens/LogueoDental.fw.png"));
   

       // lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/imagens/mrtooth-grande.png"))); // NOI18N
        lblImg.setIcon(picturePrep(bimg)); // NOI18N
      
      
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12));
        //lblUsuario.setText("Usuário:");
        lblUsuario.setText(p.getProperty(Constantes.LOGIN_USUARIO));
        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 12));
        //lblSenha.setText("Senha:");
        lblSenha.setText(p.getProperty(Constantes.LOGIN_CONTRASEÑA));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12));

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 12));

        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 12));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 12));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFundoLayout = new javax.swing.GroupLayout(jPanelFundo);
        jPanelFundo.setLayout(jPanelFundoLayout);
        jPanelFundoLayout.setHorizontalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFundoLayout.createSequentialGroup()
                                .addComponent(lblUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFundoLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                                        .addComponent(btnEntrar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLimpar))
                                    .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))
                        .addGap(31, 31, 31))
                    .addComponent(lblImg, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(57, 57, 57))
        );
        jPanelFundoLayout.setVerticalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImg)
                .addGap(29, 29, 29)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnEntrar))
                .addContainerGap())
        );

        lblImg.getAccessibleContext().setAccessibleName("lblMrTooth");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-445)/2, (screenSize.height-365)/2, 445, 365);
    }// </editor-fold>//GEN-END:initComponents

    
    public ImageIcon picturePrep(ImageIcon icon) {
        final int DESIRED_WIDTH = 300;
        double imageWidth = icon.getIconWidth();
        int imageHeight = icon.getIconHeight();
        imageWidth = DESIRED_WIDTH/imageWidth;
        imageHeight = (int) (imageWidth * imageHeight);
        Image img = icon.getImage();
        return new ImageIcon(img.getScaledInstance(DESIRED_WIDTH, imageHeight, Image.SCALE_SMOOTH));
    }
    
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        String user = txtUsuario.getText();
        String pass = txtSenha.getText();

        if(user.equals("")){
            JOptionPane.showMessageDialog(null,"O campo usuário está em branco","Atenção", JOptionPane.WARNING_MESSAGE);
        }
        else if(pass.equals("")){
            JOptionPane.showMessageDialog(null,"O campo senha está em branco","Atenção", JOptionPane.WARNING_MESSAGE);
        }
        else{
            con_login.OpenDB();
            con_login.QuerySQL("SELECT * FROM usuarios WHERE login_us = '"+user+"' AND senha_us = '"+pass+"'");
            try{
                if(con_login.rs.next()){
                    //Controle de segurança de acessos
                    String CodigoUs = (con_login.rs.getString("cod_usuario"));
                    String NomeUs = (con_login.rs.getString("nome_us"));
                    String LoginUs = (con_login.rs.getString("login_us"));
                    String TipoUs = (con_login.rs.getString("tipo_us"));
                    String Acesso = "O usuario "+NomeUs+" entrou no sistema";
                    String AcessoInsert = "INSERT INTO acessos () VALUES (NULL, '"+CodigoUs+"', '"+NomeUs+"', '"+LoginUs+"', '"+TipoUs+"', '"+Acesso+"', 'entrada', NOW())";
                    con_login.stmt.execute(AcessoInsert);
                    //Abre o formulario principal
                    new Principal().setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Usuário ou senha inválidos. Digite novamente.");
                }                
            }
            catch(SQLException erro){
                JOptionPane.showMessageDialog(null,"Erro: "+erro);
            }
            con_login.CloseDB();            
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtUsuario.setText("");
        txtSenha.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
