package mr_tooth.principal;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import mr_tooth.cadastro.*;
import mr_tooth.utilitarios.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro
 */
public class Pacientes extends javax.swing.JFrame {
    ConectaBanco con_pac;
    /** Creates new form JF_Pacientes */
    public Pacientes() {     
      initComponents();
      con_pac = new ConectaBanco();
      con_pac.OpenDB();      
      this.PreencherJtable();
    }  

    public void PreencherJtable(){
        con_pac.QuerySQL("SELECT * FROM pacientes");
        DefaultTableModel Modelo = (DefaultTableModel)jTablePacientes.getModel();
        Modelo.setNumRows(0);

        try{
            while(con_pac.rs.next()){
                Modelo.addRow(new Object [] {
                    con_pac.rs.getString("cod_paciente"),
                    con_pac.rs.getString("nome_pac"),
                    con_pac.rs.getString("rg_pac"),
                    con_pac.rs.getString("cpf_pac"),
                    con_pac.rs.getString("dtnasc_pac"),
                    con_pac.rs.getString("sexo_pac"),
                    con_pac.rs.getString("endereco_pac"),
                    con_pac.rs.getString("numero_pac"),
                    con_pac.rs.getString("cidade_pac"),
                    con_pac.rs.getString("estado_pac"),
                    con_pac.rs.getString("telefone_pac"),
                    con_pac.rs.getString("celular_pac"),
                    con_pac.rs.getString("email_pac"),
                });
            }
        }
        catch(SQLException erroTable){
            JOptionPane.showMessageDialog(null,"Erro ao carregar os pacientes cadastrados","ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pacientes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("framePacientes"); // NOI18N

        jTablePacientes.setAutoCreateRowSorter(true);
        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "RG", "CPF", "Nascimento", "Sexo", "Endereço", "Nº", "Cidade", "Estado", "Telefone ", "Celular ", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePacientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane.setViewportView(jTablePacientes);
        jTablePacientes.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTablePacientes.getColumnModel().getColumn(1).setPreferredWidth(350);
        jTablePacientes.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTablePacientes.getColumnModel().getColumn(3).setPreferredWidth(120);

        lblPesquisa.setFont(new java.awt.Font("Segoe UI", 1, 12));
        lblPesquisa.setText("Pesquisa :");

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Patient Boy 1 Search.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Patient Boy 1 Add.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Patient Boy 1 Edit 1.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Patient Boy 1 Delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addGap(27, 27, 27))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-954)/2, (screenSize.height-542)/2, 954, 542);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        new CadastroPaciente().setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        int LinhaSelecionada = this.jTablePacientes.getSelectedRow();
        String cod   = this.jTablePacientes.getValueAt(LinhaSelecionada, 0).toString();
        String nome  = this.jTablePacientes.getValueAt(LinhaSelecionada, 1).toString();
        String rg    = this.jTablePacientes.getValueAt(LinhaSelecionada, 2).toString();
        String cpf   = this.jTablePacientes.getValueAt(LinhaSelecionada, 3).toString();
        String nasc  = this.jTablePacientes.getValueAt(LinhaSelecionada, 4).toString();
        String sexo  = this.jTablePacientes.getValueAt(LinhaSelecionada, 5).toString();
        String end   = this.jTablePacientes.getValueAt(LinhaSelecionada, 6).toString();
        String num   = this.jTablePacientes.getValueAt(LinhaSelecionada, 7).toString();
        String cid   = this.jTablePacientes.getValueAt(LinhaSelecionada, 8).toString();
        String est   = this.jTablePacientes.getValueAt(LinhaSelecionada, 9).toString();
        String tel   = this.jTablePacientes.getValueAt(LinhaSelecionada, 10).toString();
        String cel   = this.jTablePacientes.getValueAt(LinhaSelecionada, 11).toString();
        String email = this.jTablePacientes.getValueAt(LinhaSelecionada, 12).toString();

        con_pac.CloseDB();

        new AlteraPaciente(cod, nome, rg, cpf, nasc, sexo, end, num, cid, est, tel, cel, email).setVisible(true);
       
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int LinhaSelecionada = this.jTablePacientes.getSelectedRow();
        String CodigoPaciente = this.jTablePacientes.getValueAt(LinhaSelecionada, 0).toString();

        try{
            //Busca no banco de dados o código do paciente selecionado para ser excluido
            String PacienteSelecionado = "SELECT * FROM pacientes WHERE cod_paciente = '"+CodigoPaciente+"'";
            con_pac.QuerySQL(PacienteSelecionado);
            con_pac.rs.next();

            //Mensagem de confirmação
            String MsgConfirmacao = "Deseja realmente excluir o paciente: "+con_pac.rs.getString("nome_pac")+" ?";
            int OpcaoEscolhida = JOptionPane.showConfirmDialog(null, MsgConfirmacao, "Excluir", JOptionPane.YES_NO_OPTION);

            if(OpcaoEscolhida == JOptionPane.YES_OPTION){
                //Excluindo o usuário após a confirmação positiva
                String ExcluirPaciente = "DELETE FROM pacientes WHERE cod_paciente = "+CodigoPaciente;
                int ExcluirSucesso  = con_pac.stmt.executeUpdate(ExcluirPaciente);

                if(ExcluirSucesso == 1){
                    JOptionPane.showMessageDialog(null,"Paciente excluido com sucesso!","Excluir!", JOptionPane.INFORMATION_MESSAGE);
                    //Atualiza jTable
                    PreencherJtable();
                }
                else{
                   //Atualiza jTable
                    PreencherJtable();
                    return;
                }
            }
            else{
                //Atualiza jTable
                PreencherJtable();
                return;
            }
        }
        catch(Exception erroSQL){
             JOptionPane.showMessageDialog(null,"Erro ao excluir", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

}
