package mr_tooth.principal;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import mr_tooth.cadastro.*;
import mr_tooth.agenda.*;
import mr_tooth.financeiro.*;
import mr_tooth.utilitarios.*;
/**
 *
 * @author Pedro
 */
public class Principal extends javax.swing.JFrame {
    String tema = "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel";
    ConectaBanco con_principal;
    /** Creates new form JF_Principal */
    Parametros p=new Parametros();
    public Principal() {
        initComponents();
        con_principal = new ConectaBanco();
        con_principal.OpenDB();
        //Selecionando o usuário logado no sistema
        con_principal.QuerySQL("SELECT * FROM acessos");
        try{
            con_principal.rs.last();
            String UsuarioLogado = (con_principal.rs.getString("nome_us"));
            //Mostrando o usuário logado
            labelUsuario.setText("Bem vindo, "+UsuarioLogado);
        }
        catch(Exception erro){             
        }      
        //Mostrando a data atual
        Data dt = new Data();
        dt.verData();
       
        labelDate.setText(dt.semana+", "+dt.dia+" de "+dt.mes+" de "+dt.ano);
        //Exibindo o tema
        LookAndFeel();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblImg = new javax.swing.JLabel();
        btnPacientes = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        btnTratamentos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanelRodape = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jItemPacientes = new javax.swing.JMenuItem();
        jItemDentistas = new javax.swing.JMenuItem();
        jItemFuncionarios = new javax.swing.JMenuItem();
        jItemUsuarios = new javax.swing.JMenuItem();
        jSeparator = new javax.swing.JPopupMenu.Separator();
        jItemConvenio = new javax.swing.JMenuItem();
        jItemTratamento = new javax.swing.JMenuItem();
        jMenuAgenda = new javax.swing.JMenu();
        jItemVerificar = new javax.swing.JMenuItem();
        jMenuFinanceiro = new javax.swing.JMenu();
        jItemPagamentos = new javax.swing.JMenuItem();
        jItemCheques = new javax.swing.JMenuItem();
        jMenuTema = new javax.swing.JMenu();
        jItemMetal = new javax.swing.JMenuItem();
        jItemMotif = new javax.swing.JMenuItem();
        jItemNimbus = new javax.swing.JMenuItem();
        jItemLiquid = new javax.swing.JMenuItem();
        jItemGTK = new javax.swing.JMenuItem();
        jItemWindows = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jItemSobre = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        //setTitle("Mr Tooth 1.0.7");
        setTitle(p.getProperty(Constantes.PRINCIPAL_TITULO));
        setBackground(new java.awt.Color(226, 225, 225));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("framePrincipal"); // NOI18N
        setResizable(false);

        jlblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/imagens/mrtooth-banner.png"))); // NOI18N

        btnPacientes.setBackground(new java.awt.Color(152, 172, 181));
        btnPacientes.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnPacientes.setForeground(new java.awt.Color(9, 68, 158));
        btnPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Patient Boy 1-48.png"))); // NOI18N
        btnPacientes.setText("Pacientes");
        btnPacientes.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnPacientes.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacientesActionPerformed(evt);
            }
        });

        btnAgenda.setBackground(new java.awt.Color(152, 172, 181));
        btnAgenda.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnAgenda.setForeground(new java.awt.Color(9, 68, 158));
        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Appointment-48.png"))); // NOI18N
        btnAgenda.setText("Agenda");
        btnAgenda.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAgenda.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });

        btnTratamentos.setBackground(new java.awt.Color(152, 172, 181));
        btnTratamentos.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnTratamentos.setForeground(new java.awt.Color(9, 68, 158));
        btnTratamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Treatment-48.png"))); // NOI18N
        btnTratamentos.setText("Tratamentos");
        btnTratamentos.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnTratamentos.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnTratamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTratamentosActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(152, 172, 181));
        btnSair.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnSair.setForeground(new java.awt.Color(9, 68, 158));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Gnome-Application-Exit-48.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSair.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanelRodape.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.disabledForeground"));
        jPanelRodape.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelRodape.setForeground(new java.awt.Color(38, 126, 226));

        labelUsuario.setText("Bem vindo, ");

        labelDate.setText("Data: ");

        javax.swing.GroupLayout jPanelRodapeLayout = new javax.swing.GroupLayout(jPanelRodape);
        jPanelRodape.setLayout(jPanelRodapeLayout);
        jPanelRodapeLayout.setHorizontalGroup(
            jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 662, Short.MAX_VALUE)
                .addComponent(labelDate)
                .addContainerGap())
        );
        jPanelRodapeLayout.setVerticalGroup(
            jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelUsuario)
                .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar.setBorder(null);

       // jMenuCadastro.setText("Cadastro");
        jMenuCadastro.setText(p.getProperty(Constantes.MENU_PRINCIPAL_REGISTRO));

        jItemPacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jItemPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Patient Boy 1.png"))); // NOI18N
        //jItemPacientes.setText("Pacientes");
        jItemPacientes.setText(p.getProperty(Constantes.MENU_PRINCIPAL_REGISTRO_PACIENTES));
        jItemPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemPacientesActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jItemPacientes);

        jItemDentistas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jItemDentistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Dentist.png"))); // NOI18N
        //jItemDentistas.setText("Dentistas");
        jItemDentistas.setText(p.getProperty(Constantes.MENU_PRINCIPAL_REGISTRO_DENTISTAS));
        
        jItemDentistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemDentistasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jItemDentistas);

        jItemFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jItemFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 2 Green.png"))); // NOI18N
        //jItemFuncionarios.setText("Funcionários");
        jItemFuncionarios.setText(p.getProperty(Constantes.MENU_PRINCIPAL_REGISTRO_ASISTENTES));
        jItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jItemFuncionarios);

        jItemUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 1 Blue.png"))); // NOI18N
        //jItemUsuarios.setText("Usuários");
        jItemUsuarios.setText(p.getProperty(Constantes.MENU_PRINCIPAL_REGISTRO_USUARIOS));
        jItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jItemUsuarios);
        jMenuCadastro.add(jSeparator);

        jItemConvenio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jItemConvenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hospital.png"))); // NOI18N
        //jItemConvenio.setText("Convenios");
        jItemConvenio.setText(p.getProperty(Constantes.MENU_PRINCIPAL_REGISTRO_CONVENIOS));
        jItemConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemConvenioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jItemConvenio);

        jItemTratamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jItemTratamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Treatment.png"))); // NOI18N
       // jItemTratamento.setText("Tratramentos");
        jItemTratamento.setText(p.getProperty(Constantes.MENU_PRINCIPAL_REGISTRO_TRATAMIENTOS));
        jItemTratamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemTratamentoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jItemTratamento);

        jMenuBar.add(jMenuCadastro);

        jMenuAgenda.setText("Agenda");

        jItemVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Calendar.png"))); // NOI18N
        jItemVerificar.setText("Verificar Consultas");
        jItemVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemVerificarActionPerformed(evt);
            }
        });
        jMenuAgenda.add(jItemVerificar);

        jMenuBar.add(jMenuAgenda);

        jMenuFinanceiro.setText("Financeiro");

        jItemPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Calendar Month.png"))); // NOI18N
        jItemPagamentos.setText("Pagamentos");
        jMenuFinanceiro.add(jItemPagamentos);

        jItemCheques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Medical Invoice 3D.png"))); // NOI18N
        jItemCheques.setText("Cheques");
        jItemCheques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemChequesActionPerformed(evt);
            }
        });
        jMenuFinanceiro.add(jItemCheques);

        jMenuBar.add(jMenuFinanceiro);

        jMenuTema.setText("Tema");

        jItemMetal.setText("Metal");
        jItemMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemMetalActionPerformed(evt);
            }
        });
        jMenuTema.add(jItemMetal);

        jItemMotif.setText("Motif");
        jItemMotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemMotifActionPerformed(evt);
            }
        });
        jMenuTema.add(jItemMotif);

        jItemNimbus.setText("Nimbus");
        jItemNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemNimbusActionPerformed(evt);
            }
        });
        jMenuTema.add(jItemNimbus);

        jItemLiquid.setText("Liquid");
        jItemLiquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemLiquidActionPerformed(evt);
            }
        });
        jMenuTema.add(jItemLiquid);

        jItemGTK.setText("GTK");
        jItemGTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemGTKActionPerformed(evt);
            }
        });
        jMenuTema.add(jItemGTK);

        jItemWindows.setText("Windows");
        jItemWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemWindowsActionPerformed(evt);
            }
        });
        jMenuTema.add(jItemWindows);

        jMenuBar.add(jMenuTema);

        jMenuAjuda.setText("Ajuda");

        jItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/imagens/proline-logo_ico.png"))); // NOI18N
        jItemSobre.setText("Sobre");
        jItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jItemSobre);

        jMenuBar.add(jMenuAjuda);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuSair);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelRodape, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(btnPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnTratamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlblImg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlblImg)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPacientes)
                    .addComponent(btnAgenda)
                    .addComponent(btnTratamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                .addComponent(jPanelRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-658)/2, 800, 658);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
         int OpcaoEscolhida = JOptionPane.showConfirmDialog(null,"Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if(OpcaoEscolhida == JOptionPane.YES_OPTION){
            try{
                con_principal.rs.last();
                //Controle de segurança de acessos
                String CodigoUs = (con_principal.rs.getString("cod_usuario"));
                String NomeUs = (con_principal.rs.getString("nome_us"));
                String LoginUs = (con_principal.rs.getString("login_us"));
                String TipoUs = (con_principal.rs.getString("tipo_us"));
                String Acesso = "O usuario "+NomeUs+" saiu do sistema";
                String AcessoInsert = "INSERT INTO acessos () VALUES (NULL, '"+CodigoUs+"', '"+NomeUs+"', '"+LoginUs+"', '"+TipoUs+"', '"+Acesso+"', 'saida', NOW())";
                con_principal.stmt.execute(AcessoInsert);
            }
            catch(Exception erro){
            }
            con_principal.CloseDB();
            System.exit(0);
        }
        else{
            return;
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jItemPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemPacientesActionPerformed
        new Pacientes().setVisible(true);
    }//GEN-LAST:event_jItemPacientesActionPerformed

    private void jItemWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemWindowsActionPerformed
        tema = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        LookAndFeel();
    }//GEN-LAST:event_jItemWindowsActionPerformed

    private void jItemNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemNimbusActionPerformed
        tema = "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel";
        LookAndFeel();
    }//GEN-LAST:event_jItemNimbusActionPerformed

    private void jItemMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemMetalActionPerformed
        tema = "javax.swing.plaf.metal.MetalLookAndFeel";
        LookAndFeel();
    }//GEN-LAST:event_jItemMetalActionPerformed

    private void jItemMotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemMotifActionPerformed
        tema = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
        LookAndFeel();
    }//GEN-LAST:event_jItemMotifActionPerformed

    private void jItemGTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemGTKActionPerformed
        tema = "com.sun.java.swing.plaf.gtk.GTKLookAndFeel";
        LookAndFeel();
    }//GEN-LAST:event_jItemGTKActionPerformed

    private void jItemLiquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemLiquidActionPerformed
        tema = "com.birosoft.liquid.LiquidLookAndFeel";
        LookAndFeel();
    }//GEN-LAST:event_jItemLiquidActionPerformed

    private void jItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemUsuariosActionPerformed
        new CadastroUsuario().setVisible(true);
    }//GEN-LAST:event_jItemUsuariosActionPerformed

    private void jItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemSobreActionPerformed
         new Sobre().setVisible(true);
    }//GEN-LAST:event_jItemSobreActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int OpcaoEscolhida = JOptionPane.showConfirmDialog(null,"Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);
        if(OpcaoEscolhida == JOptionPane.YES_OPTION){
            try{
                con_principal.rs.last();
                //Controle de segurança de acessos
                String CodigoUs = (con_principal.rs.getString("cod_usuario"));
                String NomeUs = (con_principal.rs.getString("nome_us"));
                String LoginUs = (con_principal.rs.getString("login_us"));
                String TipoUs = (con_principal.rs.getString("tipo_us"));
                String Acesso = "O usuario "+NomeUs+" saiu do sistema";
                String AcessoInsert = "INSERT INTO acessos () VALUES (NULL, '"+CodigoUs+"', '"+NomeUs+"', '"+LoginUs+"', '"+TipoUs+"', '"+Acesso+"', 'saida', NOW())";
                con_principal.stmt.execute(AcessoInsert);
            }
            catch(Exception erro){
            }
            con_principal.CloseDB();
            System.exit(0);
        }
        else{
            return;
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void jItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemFuncionariosActionPerformed
        new CadastroFuncionario().setVisible(true);
    }//GEN-LAST:event_jItemFuncionariosActionPerformed

    private void jItemTratamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemTratamentoActionPerformed
        new CadastroTratamento().setVisible(true);
    }//GEN-LAST:event_jItemTratamentoActionPerformed

    private void jItemDentistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemDentistasActionPerformed
         new CadastroDentista().setVisible(true);
    }//GEN-LAST:event_jItemDentistasActionPerformed

    private void jItemConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemConvenioActionPerformed
         new CadastroConvenio().setVisible(true);
    }//GEN-LAST:event_jItemConvenioActionPerformed

    private void jItemVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemVerificarActionPerformed
        new VerificaConsulta().setVisible(true);
    }//GEN-LAST:event_jItemVerificarActionPerformed

    private void jItemChequesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemChequesActionPerformed
        new Cheques().setVisible(true);
    }//GEN-LAST:event_jItemChequesActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        new Pacientes().setVisible(true);
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        new VerificaConsulta().setVisible(true);
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnTratamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratamentosActionPerformed
        new CadastroTratamento().setVisible(true);
    }//GEN-LAST:event_btnTratamentosActionPerformed
     public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTratamentos;
    private javax.swing.JMenuItem jItemCheques;
    private javax.swing.JMenuItem jItemConvenio;
    private javax.swing.JMenuItem jItemDentistas;
    private javax.swing.JMenuItem jItemFuncionarios;
    private javax.swing.JMenuItem jItemGTK;
    private javax.swing.JMenuItem jItemLiquid;
    private javax.swing.JMenuItem jItemMetal;
    private javax.swing.JMenuItem jItemMotif;
    private javax.swing.JMenuItem jItemNimbus;
    private javax.swing.JMenuItem jItemPacientes;
    private javax.swing.JMenuItem jItemPagamentos;
    private javax.swing.JMenuItem jItemSobre;
    private javax.swing.JMenuItem jItemTratamento;
    private javax.swing.JMenuItem jItemUsuarios;
    private javax.swing.JMenuItem jItemVerificar;
    private javax.swing.JMenuItem jItemWindows;
    private javax.swing.JMenu jMenuAgenda;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFinanceiro;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuTema;
    private javax.swing.JPanel jPanelRodape;
    private javax.swing.JPopupMenu.Separator jSeparator;
    private javax.swing.JLabel jlblImg;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables

    public void LookAndFeel(){
        //Look And Feel
        System.setProperty(
            "Quaqua.tabLayoutPolicy","wrap"
         );
         try {            
            UIManager.setLookAndFeel(tema);            
            SwingUtilities.updateComponentTreeUI(this);
        }
        catch(Exception erro) {
            JOptionPane.showMessageDialog(null,"Erro ao caregar o tema : "+erro);
        }    
    }

}

