/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SobreMrTooh.java
 *
 * Created on 15/11/2010, 20:32:58
 */

package mr_tooth.principal;

/**
 *
 * @author pedroh
 */
public class Sobre extends javax.swing.JFrame {

    /** Creates new form SobreMrTooh */
    public Sobre() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayer = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sobre");
        setResizable(false);

        jLabel1.setText("Versão : 1.0.7");
        jLabel1.setBounds(10, 370, 170, 15);
        jLayer.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Site : www.pedroh.com.br/projetos/proline");
        jLabel3.setBounds(10, 390, 320, 15);
        jLayer.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Desenvolvido por : Proline -  Soluções em desenvolvimento");
        jLabel4.setBounds(10, 410, 430, 15);
        jLayer.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("© 2009-2010 Todos os direitos reservados");
        jLabel2.setBounds(10, 430, 320, 15);
        jLayer.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/imagens/mrtooth-sobre.png"))); // NOI18N
        lblFundo.setBounds(0, 0, 440, 650);
        jLayer.add(lblFundo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayer, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-443)/2, (screenSize.height-680)/2, 443, 680);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayer;
    private javax.swing.JLabel lblFundo;
    // End of variables declaration//GEN-END:variables

}
