package mr_tooth.cadastro;
import java.io.File;
import java.sql.SQLException;
import javax.swing.*;
import mr_tooth.utilitarios.*;
/**
 *
 * @author pedroh
 */
public class CadastroDentista extends javax.swing.JFrame {
    ConectaBanco con_dent;
    /** Creates new form CadastroFuncionario */
    public CadastroDentista() {
        initComponents();
        con_dent = new ConectaBanco();
        con_dent.OpenDB();
        con_dent.QuerySQL("SELECT * FROM dentistas");

        try{
            con_dent.rs.first();
            txtCodigo.setText(con_dent.rs.getString("cod_dentista"));
            txtNome.setText(con_dent.rs.getString("nome_dent"));
            txtRG.setText(con_dent.rs.getString("rg_dent"));
            txtCPF.setText(con_dent.rs.getString("cpf_dent"));
            txtCRO.setText(con_dent.rs.getString("cro_dent"));
            txtNasc.setText(con_dent.rs.getString("dtnasc_dent"));
            cbSexo.setSelectedItem(con_dent.rs.getString("sexo_dent"));
            txtRua.setText(con_dent.rs.getString("endereco_dent"));
            txtNumero.setText(con_dent.rs.getString("numero_dent"));
            txtCidade.setText(con_dent.rs.getString("cidade_dent"));
            txtEstado.setText(con_dent.rs.getString("estado_dent"));
            txtTel.setText(con_dent.rs.getString("telefone_dent"));
            txtCel.setText(con_dent.rs.getString("celular_dent"));
            }     
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Nenhum dentista cadastrado");
        }
    }

    public void AtualizaRs(){
        try{
            con_dent.rs = con_dent.stmt.executeQuery("SELECT * FROM dentistas");
            con_dent.rs.first();
            txtCodigo.setText(con_dent.rs.getString("cod_dentista"));
            txtNome.setText(con_dent.rs.getString("nome_dent"));
            txtRG.setText(con_dent.rs.getString("rg_dent"));
            txtCPF.setText(con_dent.rs.getString("cpf_dent"));
            txtCRO.setText(con_dent.rs.getString("cro_dent"));
            txtNasc.setText(con_dent.rs.getString("dtnasc_dent"));
            cbSexo.setSelectedItem(con_dent.rs.getString("sexo_dent"));
            txtRua.setText(con_dent.rs.getString("endereco_dent"));
            txtNumero.setText(con_dent.rs.getString("numero_dent"));
            txtCidade.setText(con_dent.rs.getString("cidade_dent"));
            txtEstado.setText(con_dent.rs.getString("estado_dent"));
            txtTel.setText(con_dent.rs.getString("telefone_dent"));
            txtCel.setText(con_dent.rs.getString("celular_dent"));
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível atualizar os registros");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPesquisa = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        txtPesquisa = new javax.swing.JTextField();
        txtNasc = new javax.swing.JTextField();
        lblCel = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        btnPrimeiro = new javax.swing.JButton();
        lblRG = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtRG = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        btnPesquisa = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        lblTel = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        lblEst = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        txtEstado = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        txtRua = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        lblCRO = new javax.swing.JLabel();
        txtCRO = new javax.swing.JTextField();
        lblCaregarFoto = new javax.swing.JButton();
        jPanelFoto = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dentistas");
        setName("CadastroFuncionario"); // NOI18N
        setResizable(false);

        lblPesquisa.setText("Pesquisa :");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        lblCel.setText("Celular:");

        lblSexo.setText("* Sexo:");

        btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Primeiro_16x16.png"))); // NOI18N
        btnPrimeiro.setText("Primeiro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        lblRG.setText("* RG:");

        lblNome.setText("* Nome:");

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Dentist Search.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        lblNascimento.setText("* Data de Nascimento:");

        lblEnd.setText("Endereço:");

        txtCodigo.setEditable(false);

        lblCodigo.setText("Código:");

        lblTel.setText("* Telefone:");

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Dentist Delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblEst.setText("Estado:");

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Dentist Edit 2.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Dentist Add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Dentist Check.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblCPF.setText("* CPF:");

        lblNum.setText("Nº :");

        lblCidade.setText("Cidade:");

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Anterior_16x16.png"))); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Ultimo_16x16.png"))); // NOI18N
        btnUltimo.setText("Último");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Proximo_16x16.png"))); // NOI18N
        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        lblCRO.setText("* CRO:");

        lblCaregarFoto.setText("Foto ...");
        lblCaregarFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCaregarFotoMouseClicked(evt);
            }
        });
        lblCaregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCaregarFotoActionPerformed(evt);
            }
        });

        jPanelFoto.setBackground(java.awt.Color.lightGray);
        jPanelFoto.setPreferredSize(new java.awt.Dimension(125, 160));

        javax.swing.GroupLayout jPanelFotoLayout = new javax.swing.GroupLayout(jPanelFoto);
        jPanelFoto.setLayout(jPanelFotoLayout);
        jPanelFotoLayout.setHorizontalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        jPanelFotoLayout.setVerticalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPesquisa)
                .addGap(18, 18, 18)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(199, 199, 199))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addGap(185, 185, 185))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTel)
                                .addGap(18, 18, 18)
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCidade)
                                .addGap(33, 33, 33)
                                .addComponent(txtCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEst)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(txtNasc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(588, 588, 588))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRG)
                            .addComponent(lblNome)
                            .addComponent(lblCRO)
                            .addComponent(lblEnd)
                            .addComponent(lblSexo))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtRua, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                        .addGap(34, 34, 34)
                                        .addComponent(lblNum))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cbSexo, 0, 217, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNascimento)))
                                .addGap(179, 179, 179))
                            .addComponent(txtCRO, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCaregarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRG)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCRO))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexo)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNascimento)
                            .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnd)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCidade)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEst)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTel)
                            .addComponent(lblCel)
                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCaregarFoto)))
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(69, 69, 69))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-818)/2, (screenSize.height-576)/2, 818, 576);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        try{
            con_dent.rs.first();
            txtCodigo.setText(con_dent.rs.getString("cod_dentista"));
            txtNome.setText(con_dent.rs.getString("nome_dent"));
            txtRG.setText(con_dent.rs.getString("rg_dent"));
            txtCPF.setText(con_dent.rs.getString("cpf_dent"));
            txtCRO.setText(con_dent.rs.getString("cro_dent"));
            txtNasc.setText(con_dent.rs.getString("dtnasc_dent"));
            cbSexo.setSelectedItem(con_dent.rs.getString("sexo_dent"));
            txtRua.setText(con_dent.rs.getString("endereco_dent"));
            txtNumero.setText(con_dent.rs.getString("numero_dent"));
            txtCidade.setText(con_dent.rs.getString("cidade_dent"));
            txtEstado.setText(con_dent.rs.getString("estado_dent"));
            txtTel.setText(con_dent.rs.getString("telefone_dent"));
            txtCel.setText(con_dent.rs.getString("celular_dent"));
        } catch(SQLException erroSQL){
            JOptionPane.showMessageDialog(null,"Ops! este é o primeiro registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        //con_usuario.CloseDB();
}//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String codigoDent = txtCodigo.getText();
        try{
            //Busca no banco de dados o código do usuário selecionado para ser excluido
            String DentSelecionado = "SELECT * FROM dentistas WHERE cod_dentista = '"+codigoDent+"'";
            con_dent.QuerySQL(DentSelecionado);
            con_dent.rs.next();

            //Mensagem de confirmação
            String MsgConfirmacao = "Deseja realmente excluir o destista: "+con_dent.rs.getString("nome_dent")+" ?";
            int OpcaoEscolhida = JOptionPane.showConfirmDialog(null, MsgConfirmacao, "Excluir", JOptionPane.YES_NO_OPTION);

            if(OpcaoEscolhida == JOptionPane.YES_OPTION){
                //Excluindo o usuário após a confirmação positiva
                String ExcluirDent = "DELETE FROM dentsitas WHERE cod_dentista = '"+codigoDent+"'";
                int ExcluirSucesso  = con_dent.stmt.executeUpdate(ExcluirDent);

                if(ExcluirSucesso == 1){
                    JOptionPane.showMessageDialog(null,"Destista excluido com sucesso!","Excluir!", JOptionPane.INFORMATION_MESSAGE);
                    //Atualiza ResultSet
                    AtualizaRs();
                } else{
                    JOptionPane.showMessageDialog(null,"Não foi possível excluir o destista!", "Erro!", JOptionPane.ERROR_MESSAGE);
                    //Atualiza ResultSet
                    AtualizaRs();
                }
            } else{
                //Atualiza ResultSet
                AtualizaRs();
                return;
            }
        } catch(Exception erroSQL){
            JOptionPane.showMessageDialog(null,"Erro ao excluir", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
    try{
            String cod  = txtCodigo.getText();
            String nome  = txtNome.getText();
            String rg    = txtRG.getText();
            String cpf   = txtCPF.getText();
            String cro   = txtCRO.getText();
            String nasc  = txtNasc.getText();
            String end   = txtRua.getText();
            String num   = txtNumero.getText();
            String cid   = txtCidade.getText();
            String est   = txtEstado.getText();
            String tel   = txtTel.getText();
            String cel   = txtCel.getText();

            //Verificar se o CPF é valido
            //ValidaCPF cpf_dent = new ValidaCPF();
            //boolean cpfValidado = cpf_dent.ValidaCpf(cpf);

            //Verifica no banco de dados se já existe algum destista cadastrado com esse CPF
            //String DentistaCPF = "SELECT * FROM dentistas WHERE cpf_dent = '"+cpf+"'";
            //con_func.QuerySQL(DentistaCPF);

            if(nome.length() < 3){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu nome!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(rg.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu RG!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(rg.length() < 10){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu RG coretamente!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(cpf.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu CPF!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(cro.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu CRO!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(nasc.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o sua data de nascimento!","Atenção", JOptionPane.WARNING_MESSAGE);
            } 
            else if(nasc.length() < 10){
                JOptionPane.showMessageDialog(null,"Por favor, digite a data de nascimento coretamente! \n Ex: 01/01/1990","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(tel.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite um telefone para contato","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(tel.length() < 14){
                JOptionPane.showMessageDialog(null,"Por favor, digite o telefone coretamente! \n Ex: (11) 2910-8055","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else{
                //Atualiza os dados no banco
                String DentistaUpdate = "UPDATE dentistas SET nome_dent = '"+nome+"', rg_dent = '"+rg+"', cpf_dent = '"+cpf+"', cro_dent = '"+cro+"', dtnasc_dent = '"+nasc+"', " +
                                            "sexo_dent = '"+cbSexo.getSelectedItem()+"', foto_dent = NULL, endereco_dent = '"+end+"', numero_dent = '"+num+"', " +
                                            "cidade_dent = '"+cid+"', estado_dent = '"+est+"', telefone_dent = '"+tel+"', celular_dent = '"+cel+"'  WHERE cod_dentista = "+cod;
                con_dent.stmt.executeUpdate(DentistaUpdate);
                JOptionPane.showMessageDialog(null,"Destista atualizado com sucesso!","Atualização!", JOptionPane.INFORMATION_MESSAGE);
                //Atualiza ResultSet
                AtualizaRs();
            }
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível atualizar os dados do dentista! , "+erroSQL, "Erro!", JOptionPane.ERROR_MESSAGE);
             //Atualiza ResultSet
             AtualizaRs();
        }
}//GEN-LAST:event_btnAlterarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtCodigo.setText("");
        txtNome.setText("");
        txtRG.setText("");
        txtCPF.setText("");
        txtCRO.setText("");
        txtNasc.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtTel.setText("");
        txtCel.setText("");
        txtNome.requestFocus();
}//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try{
            String nome  = txtNome.getText();
            String rg    = txtRG.getText();
            String cpf   = txtCPF.getText();
            String cro   = txtCRO.getText();
            String nasc  = txtNasc.getText();
            String end   = txtRua.getText();
            String num   = txtNumero.getText();
            String cid   = txtCidade.getText();
            String est   = txtEstado.getText();
            String tel   = txtTel.getText();
            String cel   = txtCel.getText();

            //Verificar se o CPF é valido
            //ValidaCPF cpf_dent = new ValidaCPF();
            //boolean cpfValidado = cpf_dent.ValidaCpf(cpf);

            //Verifica no banco de dados se já existe algum dentista cadastrado com esse CPF
            String DentistaCPF = "SELECT * FROM dentistas WHERE cpf_dent = '"+cpf+"'";
            con_dent.QuerySQL(DentistaCPF);

            if(nome.length() < 3){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu nome!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(rg.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu RG!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(rg.length() < 10){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu RG coretamente!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(cpf.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu CPF!","Atenção", JOptionPane.WARNING_MESSAGE);
            }            
            else if(con_dent.rs.next()){
                JOptionPane.showMessageDialog(null,"Já existe um funcionario cadastrado com esse CPF!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(cro.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu CRO!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(nasc.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o sua data de nascimento!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(nasc.length() < 10){
                JOptionPane.showMessageDialog(null,"Por favor, digite a data de nascimento coretamente! \n Ex: 01/01/1990","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(tel.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite um telefone para contato","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(tel.length() < 14){
                JOptionPane.showMessageDialog(null,"Por favor, digite o telefone coretamente! \n Ex: (11) 2910-8055","Atenção", JOptionPane.WARNING_MESSAGE);
            } else{
                //Inseri os dados no banco
                String DentistaInsert = "INSERT INTO dentistas () VALUES (NULL,'"+nome+"','"+rg+"','"+cpf+"','"+cro+"','"+nasc+"','"+cbSexo.getSelectedItem()+"', NULL,'"+end+"','"+num+"','"+cid+"','"+est+"','"+tel+"','"+cel+"')";
                con_dent.stmt.execute(DentistaInsert);
                JOptionPane.showMessageDialog(null,"Dentista cadastrado com sucesso!","Cadastrado!", JOptionPane.INFORMATION_MESSAGE);
                //Atualiza ResultSet
                AtualizaRs();
            }
        } catch(SQLException erroSQL){
            JOptionPane.showMessageDialog(null,"Não foi possível cadastrar o desntista!"+erroSQL, "Erro!", JOptionPane.ERROR_MESSAGE);
            //Atualiza ResultSet
            AtualizaRs();
        }
}//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try{
            con_dent.rs.previous();
            txtCodigo.setText(con_dent.rs.getString("cod_dentista"));
            txtNome.setText(con_dent.rs.getString("nome_dent"));
            txtRG.setText(con_dent.rs.getString("rg_dent"));
            txtCPF.setText(con_dent.rs.getString("cpf_dent"));
            txtCRO.setText(con_dent.rs.getString("cro_dent"));
            txtNasc.setText(con_dent.rs.getString("dtnasc_dent"));
            cbSexo.setSelectedItem(con_dent.rs.getString("sexo_dent"));
            txtRua.setText(con_dent.rs.getString("endereco_dent"));
            txtNumero.setText(con_dent.rs.getString("numero_dent"));
            txtCidade.setText(con_dent.rs.getString("cidade_dent"));
            txtEstado.setText(con_dent.rs.getString("estado_dent"));
            txtTel.setText(con_dent.rs.getString("telefone_dent"));
            txtCel.setText(con_dent.rs.getString("celular_dent"));
        } catch(SQLException erroSQL){
            JOptionPane.showMessageDialog(null,"Ops! este é o primeiro registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        try{
            con_dent.rs.last();
            txtCodigo.setText(con_dent.rs.getString("cod_dentista"));
            txtNome.setText(con_dent.rs.getString("nome_dent"));
            txtRG.setText(con_dent.rs.getString("rg_dent"));
            txtCPF.setText(con_dent.rs.getString("cpf_dent"));
            txtCRO.setText(con_dent.rs.getString("cro_dent"));
            txtNasc.setText(con_dent.rs.getString("dtnasc_dent"));
            cbSexo.setSelectedItem(con_dent.rs.getString("sexo_dent"));
            txtRua.setText(con_dent.rs.getString("endereco_dent"));
            txtNumero.setText(con_dent.rs.getString("numero_dent"));
            txtCidade.setText(con_dent.rs.getString("cidade_dent"));
            txtEstado.setText(con_dent.rs.getString("estado_dent"));
            txtTel.setText(con_dent.rs.getString("telefone_dent"));
            txtCel.setText(con_dent.rs.getString("celular_dent"));
        } catch(SQLException erroSQL){
            JOptionPane.showMessageDialog(null,"Ops! este é o último registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnUltimoActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        try{
            con_dent.rs.next();
            txtCodigo.setText(con_dent.rs.getString("cod_dentista"));
            txtNome.setText(con_dent.rs.getString("nome_dent"));
            txtRG.setText(con_dent.rs.getString("rg_dent"));
            txtCPF.setText(con_dent.rs.getString("cpf_dent"));
            txtCRO.setText(con_dent.rs.getString("cro_dent"));
            txtNasc.setText(con_dent.rs.getString("dtnasc_dent"));
            cbSexo.setSelectedItem(con_dent.rs.getString("sexo_dent"));
            txtRua.setText(con_dent.rs.getString("endereco_dent"));
            txtNumero.setText(con_dent.rs.getString("numero_dent"));
            txtCidade.setText(con_dent.rs.getString("cidade_dent"));
            txtEstado.setText(con_dent.rs.getString("estado_dent"));
            txtTel.setText(con_dent.rs.getString("telefone_dent"));
            txtCel.setText(con_dent.rs.getString("celular_dent"));
        } catch(SQLException erroSQL){
            JOptionPane.showMessageDialog(null,"Ops! este é o último registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnProximoActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        try{
            con_dent.rs.first();
            String Igual = "nao";
            int TamanhoPesquisa = txtPesquisa.getText().length();

            while(Igual == "nao"){
                String Pesquisado = con_dent.rs.getString("nome_fun").substring(0,(TamanhoPesquisa));
                if(Pesquisado.equals(txtPesquisa.getText())){
                    Igual = "sim";
                }
                else{
                    con_dent.rs.next();
                }
            }
            //Mostra os dados pesquisados
            txtCodigo.setText(con_dent.rs.getString("cod_dentista"));
            txtNome.setText(con_dent.rs.getString("nome_dent"));
            txtRG.setText(con_dent.rs.getString("rg_dent"));
            txtCPF.setText(con_dent.rs.getString("cpf_dent"));
            txtCRO.setText(con_dent.rs.getString("cro_dent"));
            txtNasc.setText(con_dent.rs.getString("dtnasc_dent"));
            cbSexo.setSelectedItem(con_dent.rs.getString("sexo_dent"));
            txtRua.setText(con_dent.rs.getString("endereco_dent"));
            txtNumero.setText(con_dent.rs.getString("numero_dent"));
            txtCidade.setText(con_dent.rs.getString("cidade_dent"));
            txtEstado.setText(con_dent.rs.getString("estado_dent"));
            txtTel.setText(con_dent.rs.getString("telefone_dent"));
            txtCel.setText(con_dent.rs.getString("celular_dent"));
        }
        catch(Exception erroPesquisa){
            JOptionPane.showMessageDialog(null,"Não foi possivel localizar este dentista", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void lblCaregarFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCaregarFotoMouseClicked

}//GEN-LAST:event_lblCaregarFotoMouseClicked

    private void lblCaregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCaregarFotoActionPerformed

        String caminhoArquivo = "";

        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione a Foto");
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        File file = new File("user.dir");
        int option = arquivo.showOpenDialog(this);

        if(option == JFileChooser.APPROVE_OPTION) {
            caminhoArquivo = arquivo.getSelectedFile().getAbsolutePath();
            file = arquivo.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getPath());

            int height = image.getIconHeight();
            int width = image.getIconWidth();
            lblFoto.setSize(width, height);
            lblFoto.setIcon(image);
            lblFoto.repaint();
        } else{
            JOptionPane.showMessageDialog(null,"Você não selecionou nenhum arquivo!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lblCaregarFotoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDentista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JPanel jPanelFoto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCRO;
    private javax.swing.JButton lblCaregarFoto;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblEst;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTel;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCRO;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

}
