package mr_tooth.cadastro;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import mr_tooth.utilitarios.ConectaBanco;
/**
 *
 * @author Pedro
 */
public class CadastroUsuario extends javax.swing.JFrame {
    ConectaBanco con_usuario;
    /** Creates new form CadastroUsuario */
    public CadastroUsuario() {      
        initComponents();
        con_usuario = new ConectaBanco();
        con_usuario.OpenDB();
        con_usuario.QuerySQL("SELECT * FROM usuarios");

        try{
            con_usuario.rs.first();
            txtCodigo.setText(con_usuario.rs.getString("cod_usuario"));
            txtNome.setText(con_usuario.rs.getString("nome_us"));
            txtUsuario.setText(con_usuario.rs.getString("login_us"));
            txtSenha.setText(con_usuario.rs.getString("senha_us"));
            cbTipo.setSelectedItem(con_usuario.rs.getString("tipo_us"));
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Nenhum Usuário Cadastrado","Usuários", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void AtualizaRs(){
        try{
            con_usuario.rs = con_usuario.stmt.executeQuery("SELECT * FROM usuarios");
            con_usuario.rs.first();
            txtCodigo.setText(con_usuario.rs.getString("cod_usuario"));
            txtNome.setText(con_usuario.rs.getString("nome_us"));
            txtUsuario.setText(con_usuario.rs.getString("login_us"));
            txtSenha.setText(con_usuario.rs.getString("senha_us"));
            cbTipo.setSelectedItem(con_usuario.rs.getString("tipo_us"));
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível atualizar os registros", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        cbTipo = new javax.swing.JComboBox();
        btnSalvar = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnProximo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("usuarios"); // NOI18N
        setResizable(false);

        lblNome.setText("Nome: ");

        lblUsuario.setText("Usuário:");

        lblSenha.setText("Senha:");

        lblTipo.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Funcionario", "Dentista" }));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 1 Blue Check.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblCodigo.setText("Código:");

        txtCodigo.setEditable(false);

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Proximo_16x16.png"))); // NOI18N
        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Anterior_16x16.png"))); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 1 Blue Add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 1 Blue Edit 2.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 1 Blue Delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Ultimo_16x16.png"))); // NOI18N
        btnUltimo.setText("Último");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Primeiro_16x16.png"))); // NOI18N
        btnPrimeiro.setText("Primeiro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        lblPesquisa.setText("Pesquisa :");

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 1 Blue Search.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblUsuario)
                            .addComponent(lblSenha)
                            .addComponent(lblTipo)
                            .addComponent(lblCodigo))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(cbTipo, 0, 194, Short.MAX_VALUE)
                        .addGap(272, 272, 272))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(btnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        getAccessibleContext().setAccessibleName("usuarios");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-579)/2, (screenSize.height-468)/2, 579, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try{
            String nome    = txtNome.getText();
            String usuario = txtUsuario.getText();
            String senha   = txtSenha.getText();

            //Verifica no banco de dados se já existe algum usuário usando o login desejado
            String UsuarioLogin = "SELECT * FROM usuarios WHERE login_us = '"+usuario+"'";
            con_usuario.QuerySQL(UsuarioLogin);

            if(nome.length() < 3){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu nome!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(usuario.length() < 3){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu nome de usuário!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(usuario.length() > 16){
                JOptionPane.showMessageDialog(null,"O seu nome de usuário, não pode ter mais que 16 caracteres!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
             else if(con_usuario.rs.next()){
                JOptionPane.showMessageDialog(null,"O nome de usuário desejado já está sendo usado!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(senha.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o sua senha!","Atenção", JOptionPane.WARNING_MESSAGE);

            }
            else if(senha.length() > 8){
                JOptionPane.showMessageDialog(null,"A sua senha, não pode ter mais que 8 caracteres","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else{
                //Inseri os dados no banco
                String UsuarioInsert = "INSERT INTO usuarios () VALUES (NULL,'"+nome+"','"+usuario+"','"+senha+"','"+cbTipo.getSelectedItem()+"')";
                con_usuario.stmt.execute(UsuarioInsert);
                JOptionPane.showMessageDialog(null,"Usuário cadastrado com sucesso!","Cadastrado!", JOptionPane.INFORMATION_MESSAGE);
                //Atualiza ResultSet
                AtualizaRs();
            }
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível cadastrar o usuário!", "Erro!", JOptionPane.ERROR_MESSAGE);
             //Atualiza ResultSet
             AtualizaRs();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        try{
            con_usuario.rs.next();
            txtCodigo.setText(con_usuario.rs.getString("cod_usuario"));
            txtNome.setText(con_usuario.rs.getString("nome_us"));
            txtUsuario.setText(con_usuario.rs.getString("login_us"));
            txtSenha.setText(con_usuario.rs.getString("senha_us"));
            cbTipo.setSelectedItem(con_usuario.rs.getString("tipo_us"));
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Ops! este é o último registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try{
            con_usuario.rs.previous();
            txtCodigo.setText(con_usuario.rs.getString("cod_usuario"));
            txtNome.setText(con_usuario.rs.getString("nome_us"));
            txtUsuario.setText(con_usuario.rs.getString("login_us"));
            txtSenha.setText(con_usuario.rs.getString("senha_us"));
            cbTipo.setSelectedItem(con_usuario.rs.getString("tipo_us"));
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Ops! este é o primeiro registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtCodigo.setText("");
        txtNome.setText("");
        txtUsuario.setText("");
        txtSenha.setText("");
        cbTipo.setSelectedItem("Administrador");
        txtNome.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try{
            String codigo  = txtCodigo.getText();
            String nome    = txtNome.getText();
            String usuario = txtUsuario.getText();
            String senha   = txtSenha.getText();

            //Verifica no banco de dados se já existe algum usuário usando o login desejado
            //String UsuarioLogin = "SELECT * FROM usuarios WHERE login_us = '"+usuario+"'";
            //con_usuario.QuerySQL(UsuarioLogin);

            if(nome.length() < 3){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu nome!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(usuario.length() < 3){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu nome de usuário!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(usuario.length() > 16){
                JOptionPane.showMessageDialog(null,"O seu nome de usuário, não pode ter mais que 16 caracteres!","Atenção", JOptionPane.WARNING_MESSAGE);
            }             
            else if(senha.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o sua senha!","Atenção", JOptionPane.WARNING_MESSAGE);                
            }
            else if(senha.length() > 8){
                JOptionPane.showMessageDialog(null,"A sua senha, não pode ter mais que 8 caracteres","Atenção", JOptionPane.WARNING_MESSAGE);               
            }
            else{
                //Atualiza os dados no banco
                String UsuarioUpdate = "UPDATE usuarios SET nome_us = '"+nome+"', login_us = '"+usuario+"', senha_us = '"+senha+"', tipo_us = '"+cbTipo.getSelectedItem()+"' WHERE cod_usuario = "+codigo;
                con_usuario.stmt.executeUpdate(UsuarioUpdate);
                JOptionPane.showMessageDialog(null,"Usuário atualizado com sucesso!","Atualização!", JOptionPane.INFORMATION_MESSAGE);
                //Atualiza ResultSet
                AtualizaRs();
            }
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível atualizar os dados do usuário! , "+erroSQL, "Erro!", JOptionPane.ERROR_MESSAGE);
             //Atualiza ResultSet
             AtualizaRs();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String codigoUsuario = txtCodigo.getText();
        try{
            //Busca no banco de dados o código do usuário selecionado para ser excluido
            String UsuarioSelecionado = "SELECT * FROM usuarios WHERE cod_usuario = '"+codigoUsuario+"'";
            con_usuario.QuerySQL(UsuarioSelecionado);
            con_usuario.rs.next();

            //Mensagem de confirmação
            String MsgConfirmacao = "Deseja realmente excluir o usuário: "+con_usuario.rs.getString("login_us")+" ?";
            int OpcaoEscolhida = JOptionPane.showConfirmDialog(null, MsgConfirmacao, "Excluir", JOptionPane.YES_NO_OPTION);

            if(OpcaoEscolhida == JOptionPane.YES_OPTION){
                //Excluindo o usuário após a confirmação positiva
                String ExcluirUsuario = "DELETE FROM usuarios WHERE cod_usuario = '"+codigoUsuario+"'";
                int ExcluirSucesso  = con_usuario.stmt.executeUpdate(ExcluirUsuario);

                if(ExcluirSucesso == 1){
                    JOptionPane.showMessageDialog(null,"Usuário excluido com sucesso!","Excluir!", JOptionPane.INFORMATION_MESSAGE);
                    //Atualiza ResultSet
                    AtualizaRs();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Não foi possível excluir o usuário!", "Erro!", JOptionPane.ERROR_MESSAGE);
                    //Atualiza ResultSet
                    AtualizaRs();
                }
            }
            else{
                //Atualiza ResultSet
                AtualizaRs();
                return;
            }
        }
        catch(Exception erroSQL){
             JOptionPane.showMessageDialog(null,"Erro ao excluir", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        try{
            con_usuario.rs.last();
            txtCodigo.setText(con_usuario.rs.getString("cod_usuario"));
            txtNome.setText(con_usuario.rs.getString("nome_us"));
            txtUsuario.setText(con_usuario.rs.getString("login_us"));
            txtSenha.setText(con_usuario.rs.getString("senha_us"));
            cbTipo.setSelectedItem(con_usuario.rs.getString("tipo_us"));
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Ops! este é o último registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        try{
            con_usuario.rs.first();
            txtCodigo.setText(con_usuario.rs.getString("cod_usuario"));
            txtNome.setText(con_usuario.rs.getString("nome_us"));
            txtUsuario.setText(con_usuario.rs.getString("login_us"));
            txtSenha.setText(con_usuario.rs.getString("senha_us"));
            cbTipo.setSelectedItem(con_usuario.rs.getString("tipo_us"));
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Ops! este é o primeiro registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        //con_usuario.CloseDB();
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        try{
            con_usuario.rs.first();
            String Igual = "nao";
            int TamanhoPesquisa = txtPesquisa.getText().length();

            while(Igual == "nao"){
                String Pesquisado = con_usuario.rs.getString("nome_us").substring(0,(TamanhoPesquisa));
                if(Pesquisado.equals(txtPesquisa.getText())){
                    Igual = "sim";
                }
                else{
                    con_usuario.rs.next();
                }
            }
            //Mostra os dados pesquisados
            txtCodigo.setText(con_usuario.rs.getString("cod_usuario")); //Codigo do usuario pesquisado
            txtNome.setText(con_usuario.rs.getString("nome_us")); //Nome do usuario pesquisado
            txtUsuario.setText(con_usuario.rs.getString("login_us")); //Login do usuario pesquisado
            txtSenha.setText(con_usuario.rs.getString("senha_us")); //Senha do usuario pesquisado
            cbTipo.setSelectedItem(con_usuario.rs.getString("tipo_us")); //Tipo do usuario pesquisado
        }
        catch(Exception erroPesquisa){
            JOptionPane.showMessageDialog(null,"Não foi possivel localizar este usuário", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    
}

