package mr_tooth.cadastro;
import java.io.File;
import java.sql.*;
import javax.swing.*;
import mr_tooth.utilitarios.*;
/**
 *
 * @author Pedro
 */
public class CadastroPaciente extends javax.swing.JFrame {
    ConectaBanco con_paciente;    
    /** Creates new form JF_FichaPaciente */
    public CadastroPaciente() {
        initComponents();
        //Inicia a classe ConectaBanco
        con_paciente = new ConectaBanco();
        con_paciente.OpenDB();

        //Adiciona os convenios cadastrados no cbConvenio
        con_paciente.QuerySQL("SELECT * FROM convenios");
        try{
            while(con_paciente.rs.next()){
                cbConvenio.addItem(con_paciente.rs.getString("nome_con"));
            }
        }
        catch(Exception erroConvenio){
            JOptionPane.showMessageDialog(null,"Erro ao carregar os convenios cadastrados !", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelFicha = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        lblEnd = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEst = new javax.swing.JLabel();
        lblFone = new javax.swing.JLabel();
        lblCel = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jPanelFoto = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        lblCaregarFoto = new javax.swing.JButton();
        lblNum = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblConvenio = new javax.swing.JLabel();
        cbConvenio = new javax.swing.JComboBox();
        txtCPF = new javax.swing.JTextField();
        txtNasc = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        lblEnd1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jPanelOdontograma = new javax.swing.JPanel();
        jLabelImgOdonto = new javax.swing.JLabel();
        txt18 = new javax.swing.JTextField();
        txt17 = new javax.swing.JTextField();
        txt16 = new javax.swing.JTextField();
        txt15_55 = new javax.swing.JTextField();
        txt14_54 = new javax.swing.JTextField();
        txt13_53 = new javax.swing.JTextField();
        txt12_52 = new javax.swing.JTextField();
        txt11_51 = new javax.swing.JTextField();
        txt41_81 = new javax.swing.JTextField();
        txt42_82 = new javax.swing.JTextField();
        txt43_83 = new javax.swing.JTextField();
        txt44_84 = new javax.swing.JTextField();
        txt45_85 = new javax.swing.JTextField();
        txt46 = new javax.swing.JTextField();
        txt47 = new javax.swing.JTextField();
        txt48 = new javax.swing.JTextField();
        txt28 = new javax.swing.JTextField();
        txt27 = new javax.swing.JTextField();
        txt26 = new javax.swing.JTextField();
        txt65_25 = new javax.swing.JTextField();
        txt64_24 = new javax.swing.JTextField();
        txt63_23 = new javax.swing.JTextField();
        txt62_22 = new javax.swing.JTextField();
        txt61_21 = new javax.swing.JTextField();
        txt71_31 = new javax.swing.JTextField();
        txt72_32 = new javax.swing.JTextField();
        txt73_33 = new javax.swing.JTextField();
        txt74_34 = new javax.swing.JTextField();
        txt75_35 = new javax.swing.JTextField();
        txt36 = new javax.swing.JTextField();
        txt37 = new javax.swing.JTextField();
        txt38 = new javax.swing.JTextField();
        jPanelHistorico = new javax.swing.JPanel();
        btnSalvarPac = new javax.swing.JButton();
        btnCancelarPac = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paciente");
        setName("Paciente"); // NOI18N
        setResizable(false);

        jTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 12));

        jPanelFicha.setFont(new java.awt.Font("Segoe UI", 0, 12));

        lblNome.setText("* Nome:");

        lblRG.setText("* RG:");

        lblCPF.setText("* CPF:");

        lblNascimento.setText("* Data de Nascimento:");

        lblSexo.setText("* Sexo:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        lblEnd.setText("Endereço:");

        lblCidade.setText("Cidade:");

        lblEst.setText("Estado:");

        lblFone.setText("* Telefone:");

        lblCel.setText("Celular:");

        jPanelFoto.setBackground(java.awt.Color.lightGray);
        jPanelFoto.setPreferredSize(new java.awt.Dimension(120, 160));

        javax.swing.GroupLayout jPanelFotoLayout = new javax.swing.GroupLayout(jPanelFoto);
        jPanelFoto.setLayout(jPanelFotoLayout);
        jPanelFotoLayout.setHorizontalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelFotoLayout.setVerticalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblCaregarFoto.setText("Foto ...");
        lblCaregarFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCaregarFotoMouseClicked(evt);
            }
        });
        lblCaregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCaregarFotoActionPerformed(evt);
            }
        });

        lblNum.setText("Nº :");

        lblEmail.setText("Email:");

        lblConvenio.setText("Convenio:");

        cbConvenio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nenhum" }));

        lblEnd1.setText("Código:");

        txtCodigo.setEditable(false);

        javax.swing.GroupLayout jPanelFichaLayout = new javax.swing.GroupLayout(jPanelFicha);
        jPanelFicha.setLayout(jPanelFichaLayout);
        jPanelFichaLayout.setHorizontalGroup(
            jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCidade)
                    .addComponent(lblEmail)
                    .addComponent(lblConvenio)
                    .addGroup(jPanelFichaLayout.createSequentialGroup()
                        .addComponent(lblEnd1)
                        .addGap(579, 579, 579))
                    .addGroup(jPanelFichaLayout.createSequentialGroup()
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnd)
                            .addComponent(lblRG)
                            .addComponent(lblNome)
                            .addComponent(lblSexo)
                            .addComponent(lblFone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaLayout.createSequentialGroup()
                                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCel, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                            .addComponent(cbConvenio, 0, 546, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaLayout.createSequentialGroup()
                                .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelFichaLayout.createSequentialGroup()
                                        .addComponent(lblNascimento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNasc))
                                    .addGroup(jPanelFichaLayout.createSequentialGroup()
                                        .addComponent(lblCPF)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelFichaLayout.createSequentialGroup()
                                .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelFichaLayout.createSequentialGroup()
                                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblEst))
                                    .addComponent(txtRua, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addGroup(jPanelFichaLayout.createSequentialGroup()
                                        .addComponent(lblNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(lblCaregarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelFichaLayout.setVerticalGroup(
            jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFichaLayout.createSequentialGroup()
                        .addComponent(jPanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCaregarFoto))
                    .addGroup(jPanelFichaLayout.createSequentialGroup()
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnd1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRG)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexo)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNascimento)
                            .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnd)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNum)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCidade)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEst)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFone)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCel)
                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConvenio)
                            .addComponent(cbConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(327, 327, 327))
        );

        jTabbedPane.addTab("Ficha do Paciente", new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Patient Boy 1.png")), jPanelFicha); // NOI18N

        jLabelImgOdonto.setFont(new java.awt.Font("Arial", 0, 10));
        jLabelImgOdonto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/imagens/mrtooth-odontograma_maior.png"))); // NOI18N
        jLabelImgOdonto.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txt18.setFont(new java.awt.Font("Arial", 0, 10));

        txt17.setFont(new java.awt.Font("Arial", 0, 10));

        txt16.setFont(new java.awt.Font("Arial", 0, 10));

        txt15_55.setFont(new java.awt.Font("Arial", 0, 10));

        txt14_54.setFont(new java.awt.Font("Arial", 0, 10));

        txt13_53.setFont(new java.awt.Font("Arial", 0, 10));

        txt12_52.setFont(new java.awt.Font("Arial", 0, 10));

        txt11_51.setFont(new java.awt.Font("Arial", 0, 10));

        txt41_81.setFont(new java.awt.Font("Arial", 0, 10));

        txt42_82.setFont(new java.awt.Font("Arial", 0, 10));

        txt43_83.setFont(new java.awt.Font("Arial", 0, 10));

        txt44_84.setFont(new java.awt.Font("Arial", 0, 10));

        txt45_85.setFont(new java.awt.Font("Arial", 0, 10));

        txt46.setFont(new java.awt.Font("Arial", 0, 10));

        txt47.setFont(new java.awt.Font("Arial", 0, 10));

        txt48.setFont(new java.awt.Font("Arial", 0, 10));

        txt28.setFont(new java.awt.Font("Arial", 0, 10));

        txt27.setFont(new java.awt.Font("Arial", 0, 10));

        txt26.setFont(new java.awt.Font("Arial", 0, 10));

        txt65_25.setFont(new java.awt.Font("Arial", 0, 10));

        txt64_24.setFont(new java.awt.Font("Arial", 0, 10));

        txt63_23.setFont(new java.awt.Font("Arial", 0, 10));

        txt62_22.setFont(new java.awt.Font("Arial", 0, 10));

        txt61_21.setFont(new java.awt.Font("Arial", 0, 10));

        txt71_31.setFont(new java.awt.Font("Arial", 0, 10));

        txt72_32.setFont(new java.awt.Font("Arial", 0, 10));

        txt73_33.setFont(new java.awt.Font("Arial", 0, 10));

        txt74_34.setFont(new java.awt.Font("Arial", 0, 10));

        txt75_35.setFont(new java.awt.Font("Arial", 0, 10));

        txt36.setFont(new java.awt.Font("Arial", 0, 10));

        txt37.setFont(new java.awt.Font("Arial", 0, 10));

        txt38.setFont(new java.awt.Font("Arial", 0, 10));

        javax.swing.GroupLayout jPanelOdontogramaLayout = new javax.swing.GroupLayout(jPanelOdontograma);
        jPanelOdontograma.setLayout(jPanelOdontogramaLayout);
        jPanelOdontogramaLayout.setHorizontalGroup(
            jPanelOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOdontogramaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanelOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt18, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt15_55, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt14_54, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt13_53, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt12_52, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt11_51, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt41_81, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt42_82, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt43_83, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt44_84, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt45_85, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt46, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt47, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt48, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImgOdonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt38, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt37, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt36, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt75_35, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt74_34, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt73_33, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt72_32, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt71_31, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt61_21, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt62_22, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt63_23, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt64_24, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt65_25, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt27, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt28, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanelOdontogramaLayout.setVerticalGroup(
            jPanelOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOdontogramaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOdontogramaLayout.createSequentialGroup()
                        .addComponent(txt18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt15_55, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt14_54, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt13_53, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt12_52, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt11_51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt41_81, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt42_82, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt43_83, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt44_84, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt45_85, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt46, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt47, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt48, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOdontogramaLayout.createSequentialGroup()
                        .addComponent(txt28, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt65_25, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt64_24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt63_23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt62_22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt61_21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt71_31, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt72_32, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt73_33, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt74_34, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt75_35, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt36, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelImgOdonto))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Odontograma", new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Tooth 2.png")), jPanelOdontograma); // NOI18N

        javax.swing.GroupLayout jPanelHistoricoLayout = new javax.swing.GroupLayout(jPanelHistorico);
        jPanelHistorico.setLayout(jPanelHistoricoLayout);
        jPanelHistoricoLayout.setHorizontalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        jPanelHistoricoLayout.setVerticalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Histórico", new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Calendar Statistics.png")), jPanelHistorico); // NOI18N

        btnSalvarPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Patient Boy 1 Check.png"))); // NOI18N
        btnSalvarPac.setText("Salvar");
        btnSalvarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarPacActionPerformed(evt);
            }
        });

        btnCancelarPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Patient Boy 1 Stop.png"))); // NOI18N
        btnCancelarPac.setText("Cancelar");
        btnCancelarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(btnSalvarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCancelarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarPac)
                    .addComponent(btnSalvarPac))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-827)/2, (screenSize.height-675)/2, 827, 675);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCaregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCaregarFotoActionPerformed
        
        String caminhoArquivo = "";

        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione a Foto");
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        File file = new File("user.dir");
        int option = arquivo.showOpenDialog(this);

        if(option == JFileChooser.APPROVE_OPTION) {
            caminhoArquivo = arquivo.getSelectedFile().getAbsolutePath();
            file = arquivo.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getPath());

            int height = image.getIconHeight();
            int width = image.getIconWidth();
            lblFoto.setSize(width, height);
            lblFoto.setIcon(image);            
            lblFoto.repaint();
        }
        else{
            JOptionPane.showMessageDialog(null,"Você não selecionou nenhum arquivo!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_lblCaregarFotoActionPerformed

    private void lblCaregarFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCaregarFotoMouseClicked
      
    }//GEN-LAST:event_lblCaregarFotoMouseClicked

    private void btnSalvarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPacActionPerformed

        //Salvar dados paciente
        try{
            String cod   = txtCodigo.getText();
            String nome  = txtNome.getText();
            String rg    = txtRG.getText();
            String cpf   = txtCPF.getText();
            String nasc  = txtNasc.getText();
            String end   = txtRua.getText();
            String num   = txtNumero.getText();
            String cid   = txtCidade.getText();
            String est   = txtEstado.getText();
            String tel   = txtTel.getText();
            String cel   = txtCel.getText();
            String email = txtEmail.getText();

            //Verificar se o CPF é valido
            //ValidaCPF cpf_paciente = new ValidaCPF();
            //boolean cpfValidado = cpf_paciente.ValidaCpf(cpf);

            //Verifica no banco de dados se já existe algum paciente cadastrado com esse CPF
            String PacienteCPF = "SELECT * FROM pacientes WHERE cpf_pac = '"+cpf+"'";
            con_paciente.QuerySQL(PacienteCPF);

            if(nome.length() < 3){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu nome!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(rg.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu RG!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(rg.length() < 10){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu RG coretamente!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(cpf.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu CPF!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            /*
             else if(cpfValidado = false){
                JOptionPane.showMessageDialog(null,"O número CPF digitado é invalido!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            */
            else if(con_paciente.rs.next()){
                JOptionPane.showMessageDialog(null,"Já existe um paciente cadastrado com esse CPF!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(nasc.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o sua data de nascimento!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(nasc.length() < 10){
                JOptionPane.showMessageDialog(null,"Por favor, digite a data de nascimento coretamente! \n Ex: 01/01/1990","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(tel.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite um telefone para contato","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(tel.length() < 14){
                JOptionPane.showMessageDialog(null,"Por favor, digite o telefone coretamente! \n Ex: (11) 2910-8055","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else{
                //Inseri os dados no banco
                String PacienteInsert = "INSERT INTO pacientes () VALUES (NULL,'"+nome+"','"+rg+"','"+cpf+"','"+nasc+"','"+cbSexo.getSelectedItem()+"', NULL,'"+end+"','"+num+"','"+cid+"','"+est+"','"+tel+"','"+cel+"','"+email+"','"+cbConvenio.getSelectedItem()+"')";
                con_paciente.stmt.execute(PacienteInsert);
                JOptionPane.showMessageDialog(null,"Paciente cadastrado com sucesso!","Cadastrado!", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível cadastrar o usuário!"+erroSQL, "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        
        //Salvar dados odontograma
        try{
            String cod   = txtCodigo.getText();
            String nome  = txtNome.getText();

            //Inseri os dados no banco
            String OdontoInsert = "INSERT INTO odontograma () VALUES (" +
                                  "NULL,LAST_INSERT_ID(),'"+nome+"'," +
                                  "'"+txt18.getText()+"'," +
                                  "'"+txt17.getText()+"'," +
                                  "'"+txt16.getText()+"'," +
                                  "'"+txt15_55.getText()+"'," +
                                  "'"+txt14_54.getText()+"'," +
                                  "'"+txt13_53.getText()+"'," +
                                  "'"+txt12_52.getText()+"'," +
                                  "'"+txt11_51.getText()+"'," +
                                  "'"+txt41_81.getText()+"'," +
                                  "'"+txt42_82.getText()+"'," +
                                  "'"+txt43_83.getText()+"'," +
                                  "'"+txt44_84.getText()+"'," +
                                  "'"+txt45_85.getText()+"'," +
                                  "'"+txt46.getText()+"'," +
                                  "'"+txt47.getText()+"'," +
                                  "'"+txt48.getText()+"'," +
                                  "'"+txt28.getText()+"'," +
                                  "'"+txt27.getText()+"'," +
                                  "'"+txt26.getText()+"'," +
                                  "'"+txt65_25.getText()+"'," +
                                  "'"+txt64_24.getText()+"'," +
                                  "'"+txt63_23.getText()+"'," +
                                  "'"+txt62_22.getText()+"'," +
                                  "'"+txt61_21.getText()+"'," +
                                  "'"+txt71_31.getText()+"'," +
                                  "'"+txt72_32.getText()+"'," +
                                  "'"+txt73_33.getText()+"'," +
                                  "'"+txt74_34.getText()+"'," +
                                  "'"+txt75_35.getText()+"'," +
                                  "'"+txt36.getText()+"'," +
                                  "'"+txt37.getText()+"'," +
                                  "'"+txt38.getText()+"')";

            con_paciente.stmt.execute(OdontoInsert);
            JOptionPane.showMessageDialog(null,"Odontograma do paciente cadastrado com sucesso!","Cadastrado!", JOptionPane.INFORMATION_MESSAGE);

        }
        catch(Exception erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível salvar os dados do odontograma!"+erroSQL, "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSalvarPacActionPerformed

    private void btnCancelarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPacActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarPacActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPac;
    private javax.swing.JButton btnSalvarPac;
    private javax.swing.JComboBox cbConvenio;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JLabel jLabelImgOdonto;
    private javax.swing.JPanel jPanelFicha;
    private javax.swing.JPanel jPanelFoto;
    private javax.swing.JPanel jPanelHistorico;
    private javax.swing.JPanel jPanelOdontograma;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JButton lblCaregarFoto;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblConvenio;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblEnd1;
    private javax.swing.JLabel lblEst;
    private javax.swing.JLabel lblFone;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JTextField txt11_51;
    private javax.swing.JTextField txt12_52;
    private javax.swing.JTextField txt13_53;
    private javax.swing.JTextField txt14_54;
    private javax.swing.JTextField txt15_55;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt17;
    private javax.swing.JTextField txt18;
    private javax.swing.JTextField txt26;
    private javax.swing.JTextField txt27;
    private javax.swing.JTextField txt28;
    private javax.swing.JTextField txt36;
    private javax.swing.JTextField txt37;
    private javax.swing.JTextField txt38;
    private javax.swing.JTextField txt41_81;
    private javax.swing.JTextField txt42_82;
    private javax.swing.JTextField txt43_83;
    private javax.swing.JTextField txt44_84;
    private javax.swing.JTextField txt45_85;
    private javax.swing.JTextField txt46;
    private javax.swing.JTextField txt47;
    private javax.swing.JTextField txt48;
    private javax.swing.JTextField txt61_21;
    private javax.swing.JTextField txt62_22;
    private javax.swing.JTextField txt63_23;
    private javax.swing.JTextField txt64_24;
    private javax.swing.JTextField txt65_25;
    private javax.swing.JTextField txt71_31;
    private javax.swing.JTextField txt72_32;
    private javax.swing.JTextField txt73_33;
    private javax.swing.JTextField txt74_34;
    private javax.swing.JTextField txt75_35;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

}
