package mr_tooth.cadastro;
import java.io.File;
import java.sql.SQLException;
import javax.swing.*;
import mr_tooth.utilitarios.*;
/**
 *
 * @author pedroh
 */
public class CadastroFuncionario extends javax.swing.JFrame {
    ConectaBanco con_func;
    /** Creates new form CadastroFuncionario */
    public CadastroFuncionario() {
        initComponents();
        con_func = new ConectaBanco();
        con_func.OpenDB();
        con_func.QuerySQL("SELECT * FROM funcionarios");

        try{
            con_func.rs.first();
            txtCodigo.setText(con_func.rs.getString("cod_funcionario"));
            txtNome.setText(con_func.rs.getString("nome_fun"));
            txtRG.setText(con_func.rs.getString("rg_fun"));
            txtCPF.setText(con_func.rs.getString("cpf_fun"));
            cbSexo.setSelectedItem(con_func.rs.getString("sexo_fun"));
            txtNasc.setText(con_func.rs.getString("dtnasc_fun"));
            txtRua.setText(con_func.rs.getString("endereco_fun"));
            txtNumero.setText(con_func.rs.getString("numero_fun"));
            txtCidade.setText(con_func.rs.getString("cidade_fun"));
            txtEstado.setText(con_func.rs.getString("estado_fun"));
            txtTel.setText(con_func.rs.getString("telefone_fun"));
            txtCel.setText(con_func.rs.getString("celular_fun"));
            }     
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Nenhum Funcionario Cadastrado");
        }
    }

    public void AtualizaRs(){
        try{
            con_func.rs = con_func.stmt.executeQuery("SELECT * FROM funcionarios");
            con_func.rs.first();
            txtCodigo.setText(con_func.rs.getString("cod_funcionario"));
            txtNome.setText(con_func.rs.getString("nome_fun"));
            txtRG.setText(con_func.rs.getString("rg_fun"));
            txtCPF.setText(con_func.rs.getString("cpf_fun"));
            cbSexo.setSelectedItem(con_func.rs.getString("sexo_fun"));
            txtNasc.setText(con_func.rs.getString("dtnasc_fun"));
            txtRua.setText(con_func.rs.getString("endereco_fun"));
            txtNumero.setText(con_func.rs.getString("numero_fun"));
            txtCidade.setText(con_func.rs.getString("cidade_fun"));
            txtEstado.setText(con_func.rs.getString("estado_fun"));
            txtTel.setText(con_func.rs.getString("telefone_fun"));
            txtCel.setText(con_func.rs.getString("celular_fun"));
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível atualizar os registros");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPesquisa = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        txtPesquisa = new javax.swing.JTextField();
        txtNasc = new javax.swing.JTextField();
        lblCel = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtCel = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        btnPrimeiro = new javax.swing.JButton();
        lblRG = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtRG = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        btnPesquisa = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        lblTel = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        lblEst = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        txtEstado = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblCaregarFoto = new javax.swing.JButton();
        txtRua = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        jPanelFoto = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionarios");
        setName("CadastroFuncionario"); // NOI18N
        setResizable(false);

        lblPesquisa.setText("Pesquisa :");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        lblCel.setText("Celular:");

        lblSexo.setText("* Sexo:");

        btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Primeiro_16x16.png"))); // NOI18N
        btnPrimeiro.setText("Primeiro");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        lblRG.setText("* RG:");

        lblNome.setText("* Nome:");

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 2 Green Search.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        lblNascimento.setText("* Data de Nascimento:");

        lblEnd.setText("Endereço:");

        txtCodigo.setEditable(false);

        lblCodigo.setText("Código:");

        lblTel.setText("* Telefone:");

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 1 Green Delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblEst.setText("Estado:");

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 1 Green Edit 2.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 1 Green Add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Hygienist 1 Green Check.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblCPF.setText("* CPF:");

        lblNum.setText("Nº :");

        lblCidade.setText("Cidade:");

        lblCaregarFoto.setText("Foto ...");
        lblCaregarFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCaregarFotoMouseClicked(evt);
            }
        });
        lblCaregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCaregarFotoActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Anterior_16x16.png"))); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Ultimo_16x16.png"))); // NOI18N
        btnUltimo.setText("Último");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Proximo_16x16.png"))); // NOI18N
        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        jPanelFoto.setBackground(java.awt.Color.lightGray);
        jPanelFoto.setPreferredSize(new java.awt.Dimension(120, 160));

        javax.swing.GroupLayout jPanelFotoLayout = new javax.swing.GroupLayout(jPanelFoto);
        jPanelFoto.setLayout(jPanelFotoLayout);
        jPanelFotoLayout.setHorizontalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
            .addGroup(jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelFotoLayout.setVerticalGroup(
            jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(jPanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCidade)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(579, 579, 579))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnd)
                            .addComponent(lblRG)
                            .addComponent(lblNome)
                            .addComponent(lblSexo)
                            .addComponent(lblTel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRG, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(cbSexo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCPF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNum)
                                            .addComponent(lblNascimento))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNasc)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(btnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtRua, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addGap(267, 267, 267))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblCel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCel))
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblEst)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(txtEstado)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCaregarFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPesquisa)
                .addGap(18, 18, 18)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addGap(199, 199, 199))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lblCaregarFoto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRG)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexo)
                            .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNascimento)
                            .addComponent(txtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnd)
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCidade)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEst)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTel)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCel)
                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-798)/2, (screenSize.height-533)/2, 798, 533);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        try{
            con_func.rs.first();
            txtCodigo.setText(con_func.rs.getString("cod_funcionario"));
            txtNome.setText(con_func.rs.getString("nome_fun"));
            txtRG.setText(con_func.rs.getString("rg_fun"));
            txtCPF.setText(con_func.rs.getString("cpf_fun"));
            cbSexo.setSelectedItem(con_func.rs.getString("sexo_fun"));
            txtNasc.setText(con_func.rs.getString("dtnasc_fun"));
            txtRua.setText(con_func.rs.getString("endereco_fun"));
            txtNumero.setText(con_func.rs.getString("numero_fun"));
            txtCidade.setText(con_func.rs.getString("cidade_fun"));
            txtEstado.setText(con_func.rs.getString("estado_fun"));
            txtTel.setText(con_func.rs.getString("telefone_fun"));
            txtCel.setText(con_func.rs.getString("celular_fun"));
        } catch(SQLException erroSQL){
            JOptionPane.showMessageDialog(null,"Ops! este é o primeiro registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        //con_usuario.CloseDB();
}//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String codigoFunc = txtCodigo.getText();
        try{
            //Busca no banco de dados o código do usuário selecionado para ser excluido
            String FuncSelecionado = "SELECT * FROM funcionarios WHERE cod_funcionario = '"+codigoFunc+"'";
            con_func.QuerySQL(FuncSelecionado);
            con_func.rs.next();

            //Mensagem de confirmação
            String MsgConfirmacao = "Deseja realmente excluir o funcionario: "+con_func.rs.getString("nome_fun")+" ?";
            int OpcaoEscolhida = JOptionPane.showConfirmDialog(null, MsgConfirmacao, "Excluir", JOptionPane.YES_NO_OPTION);

            if(OpcaoEscolhida == JOptionPane.YES_OPTION){
                //Excluindo o usuário após a confirmação positiva
                String ExcluirFunc = "DELETE FROM funcionarios WHERE cod_usuario = '"+codigoFunc+"'";
                int ExcluirSucesso  = con_func.stmt.executeUpdate(ExcluirFunc);

                if(ExcluirSucesso == 1){
                    JOptionPane.showMessageDialog(null,"Funcionario excluido com sucesso!","Excluir!", JOptionPane.INFORMATION_MESSAGE);
                    //Atualiza ResultSet
                    AtualizaRs();
                } else{
                    JOptionPane.showMessageDialog(null,"Não foi possível excluir o funcionario!", "Erro!", JOptionPane.ERROR_MESSAGE);
                    //Atualiza ResultSet
                    AtualizaRs();
                }
            } else{
                //Atualiza ResultSet
                AtualizaRs();
                return;
            }
        } catch(Exception erroSQL){
            JOptionPane.showMessageDialog(null,"Erro ao excluir", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
    try{
            String cod  = txtCodigo.getText();
            String nome  = txtNome.getText();
            String rg    = txtRG.getText();
            String cpf   = txtCPF.getText();
            String nasc  = txtNasc.getText();
            String end   = txtRua.getText();
            String num   = txtNumero.getText();
            String cid   = txtCidade.getText();
            String est   = txtEstado.getText();
            String tel   = txtTel.getText();
            String cel   = txtCel.getText();

            //Verificar se o CPF é valido
            //ValidaCPF cpf_func = new ValidaCPF();
            //boolean cpfValidado = cpf_func.ValidaCpf(cpf);

            //Verifica no banco de dados se já existe algum funcionario cadastrado com esse CPF
            //String FuncionarioCPF = "SELECT * FROM funcionarios WHERE cpf_fun = '"+cpf+"'";
            //con_func.QuerySQL(FuncionarioCPF);

            if(nome.length() < 3){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu nome!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(rg.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu RG!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(rg.length() < 10){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu RG coretamente!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(cpf.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu CPF!","Atenção", JOptionPane.WARNING_MESSAGE);
            }        
            else if(nasc.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o sua data de nascimento!","Atenção", JOptionPane.WARNING_MESSAGE);
            } 
            else if(nasc.length() < 10){
                JOptionPane.showMessageDialog(null,"Por favor, digite a data de nascimento coretamente! \n Ex: 01/01/1990","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(tel.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite um telefone para contato","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(tel.length() < 14){
                JOptionPane.showMessageDialog(null,"Por favor, digite o telefone coretamente! \n Ex: (11) 2910-8055","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else{
                //Atualiza os dados no banco
                String FuncionarioUpdate = "UPDATE funcionarios SET nome_fun = '"+nome+"', rg_fun = '"+rg+"', cpf_fun = '"+cpf+"', dtnasc_fun = '"+nasc+"', " +
                                            "sexo_fun = '"+cbSexo.getSelectedItem()+"', foto_fun = NULL, endereco_fun = '"+end+"', numero_fun = '"+num+"', " +
                                            "cidade_fun = '"+cid+"', estado_fun = '"+est+"', telefone_fun = '"+tel+"', celular_fun = '"+cel+"'  WHERE cod_funcionario = "+cod;
                con_func.stmt.executeUpdate(FuncionarioUpdate);
                JOptionPane.showMessageDialog(null,"Funcionario atualizado com sucesso!","Atualização!", JOptionPane.INFORMATION_MESSAGE);
                //Atualiza ResultSet
                AtualizaRs();
            }
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível atualizar os dados do funcionario! , "+erroSQL, "Erro!", JOptionPane.ERROR_MESSAGE);
             //Atualiza ResultSet
             AtualizaRs();
        }
}//GEN-LAST:event_btnAlterarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtCodigo.setText("");
        txtNome.setText("");
        txtRG.setText("");
        txtCPF.setText("");
        txtNasc.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtTel.setText("");
        txtCel.setText("");
        txtNome.requestFocus();
}//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try{
            String nome  = txtNome.getText();
            String rg    = txtRG.getText();
            String cpf   = txtCPF.getText();
            String nasc  = txtNasc.getText();
            String end   = txtRua.getText();
            String num   = txtNumero.getText();
            String cid   = txtCidade.getText();
            String est   = txtEstado.getText();
            String tel   = txtTel.getText();
            String cel   = txtCel.getText();

            //Verificar se o CPF é valido
            //ValidaCPF cpf_func = new ValidaCPF();
            //boolean cpfValidado = cpf_func.ValidaCpf(cpf);

            //Verifica no banco de dados se já existe algum funcionario cadastrado com esse CPF
            String FuncionarioCPF = "SELECT * FROM funcionarios WHERE cpf_fun = '"+cpf+"'";
            con_func.QuerySQL(FuncionarioCPF);

            if(nome.length() < 3){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu nome!","Atenção", JOptionPane.WARNING_MESSAGE);
            } else if(rg.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu RG!","Atenção", JOptionPane.WARNING_MESSAGE);
            } else if(rg.length() < 10){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu RG coretamente!","Atenção", JOptionPane.WARNING_MESSAGE);
            } else if(cpf.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o seu CPF!","Atenção", JOptionPane.WARNING_MESSAGE);
            }            
            else if(con_func.rs.next()){
                JOptionPane.showMessageDialog(null,"Já existe um funcionario cadastrado com esse CPF!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(nasc.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o sua data de nascimento!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(nasc.length() < 10){
                JOptionPane.showMessageDialog(null,"Por favor, digite a data de nascimento coretamente! \n Ex: 01/01/1990","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(tel.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite um telefone para contato","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(tel.length() < 14){
                JOptionPane.showMessageDialog(null,"Por favor, digite o telefone coretamente! \n Ex: (11) 2910-8055","Atenção", JOptionPane.WARNING_MESSAGE);
            } else{
                //Inseri os dados no banco
                String FuncionarioInsert = "INSERT INTO funcionarios () VALUES (NULL,'"+nome+"','"+rg+"','"+cpf+"','"+nasc+"','"+cbSexo.getSelectedItem()+"', NULL,'"+end+"','"+num+"','"+cid+"','"+est+"','"+tel+"','"+cel+"')";
                con_func.stmt.execute(FuncionarioInsert);
                JOptionPane.showMessageDialog(null,"Funcionario cadastrado com sucesso!","Cadastrado!", JOptionPane.INFORMATION_MESSAGE);
                //Atualiza ResultSet
                AtualizaRs();
            }
        } catch(SQLException erroSQL){
            JOptionPane.showMessageDialog(null,"Não foi possível cadastrar o usuário!"+erroSQL, "Erro!", JOptionPane.ERROR_MESSAGE);
            //Atualiza ResultSet
            AtualizaRs();
        }
}//GEN-LAST:event_btnSalvarActionPerformed

    private void lblCaregarFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCaregarFotoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCaregarFotoMouseClicked

    private void lblCaregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCaregarFotoActionPerformed

        String caminhoArquivo = "";

        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione a Foto");
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        File file = new File("user.dir");
        int option = arquivo.showOpenDialog(this);

        if(option == JFileChooser.APPROVE_OPTION) {
            caminhoArquivo = arquivo.getSelectedFile().getAbsolutePath();
            file = arquivo.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getPath());

            int height = image.getIconHeight();
            int width = image.getIconWidth();
            lblFoto.setSize(width, height);
            lblFoto.setIcon(image);
            lblFoto.repaint();
        } else{
            JOptionPane.showMessageDialog(null,"Você não selecionou nenhum arquivo!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_lblCaregarFotoActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        try{
            con_func.rs.previous();
            txtCodigo.setText(con_func.rs.getString("cod_funcionario"));
            txtNome.setText(con_func.rs.getString("nome_fun"));
            txtRG.setText(con_func.rs.getString("rg_fun"));
            txtCPF.setText(con_func.rs.getString("cpf_fun"));
            cbSexo.setSelectedItem(con_func.rs.getString("sexo_fun"));
            txtNasc.setText(con_func.rs.getString("dtnasc_fun"));
            txtRua.setText(con_func.rs.getString("endereco_fun"));
            txtNumero.setText(con_func.rs.getString("numero_fun"));
            txtCidade.setText(con_func.rs.getString("cidade_fun"));
            txtEstado.setText(con_func.rs.getString("estado_fun"));
            txtTel.setText(con_func.rs.getString("telefone_fun"));
            txtCel.setText(con_func.rs.getString("celular_fun"));
        } catch(SQLException erroSQL){
            JOptionPane.showMessageDialog(null,"Ops! este é o primeiro registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        try{
            con_func.rs.last();           
            txtCodigo.setText(con_func.rs.getString("cod_funcionario"));
            txtNome.setText(con_func.rs.getString("nome_fun"));
            txtRG.setText(con_func.rs.getString("rg_fun"));
            txtCPF.setText(con_func.rs.getString("cpf_fun"));
            cbSexo.setSelectedItem(con_func.rs.getString("sexo_fun"));
            txtNasc.setText(con_func.rs.getString("dtnasc_fun"));
            txtRua.setText(con_func.rs.getString("endereco_fun"));
            txtNumero.setText(con_func.rs.getString("numero_fun"));
            txtCidade.setText(con_func.rs.getString("cidade_fun"));
            txtEstado.setText(con_func.rs.getString("estado_fun"));
            txtTel.setText(con_func.rs.getString("telefone_fun"));
            txtCel.setText(con_func.rs.getString("celular_fun"));
        } catch(SQLException erroSQL){
            JOptionPane.showMessageDialog(null,"Ops! este é o último registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnUltimoActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        try{
            con_func.rs.next();            
            txtCodigo.setText(con_func.rs.getString("cod_funcionario"));
            txtNome.setText(con_func.rs.getString("nome_fun"));
            txtRG.setText(con_func.rs.getString("rg_fun"));
            txtCPF.setText(con_func.rs.getString("cpf_fun"));
            cbSexo.setSelectedItem(con_func.rs.getString("sexo_fun"));
            txtNasc.setText(con_func.rs.getString("dtnasc_fun"));
            txtRua.setText(con_func.rs.getString("endereco_fun"));
            txtNumero.setText(con_func.rs.getString("numero_fun"));
            txtCidade.setText(con_func.rs.getString("cidade_fun"));
            txtEstado.setText(con_func.rs.getString("estado_fun"));
            txtTel.setText(con_func.rs.getString("telefone_fun"));
            txtCel.setText(con_func.rs.getString("celular_fun"));
        } catch(SQLException erroSQL){
            JOptionPane.showMessageDialog(null,"Ops! este é o último registro!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnProximoActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        try{
            con_func.rs.first();
            String Igual = "nao";
            int TamanhoPesquisa = txtPesquisa.getText().length();

            while(Igual == "nao"){
                String Pesquisado = con_func.rs.getString("nome_fun").substring(0,(TamanhoPesquisa));
                if(Pesquisado.equals(txtPesquisa.getText())){
                    Igual = "sim";
                }
                else{
                    con_func.rs.next();
                }
            }
            //Mostra os dados pesquisados
            txtCodigo.setText(con_func.rs.getString("cod_funcionario"));
            txtNome.setText(con_func.rs.getString("nome_fun"));
            txtRG.setText(con_func.rs.getString("rg_fun"));
            txtCPF.setText(con_func.rs.getString("cpf_fun"));
            cbSexo.setSelectedItem(con_func.rs.getString("sexo_fun"));
            txtNasc.setText(con_func.rs.getString("dtnasc_fun"));
            txtRua.setText(con_func.rs.getString("endereco_fun"));
            txtNumero.setText(con_func.rs.getString("numero_fun"));
            txtCidade.setText(con_func.rs.getString("cidade_fun"));
            txtEstado.setText(con_func.rs.getString("estado_fun"));
            txtTel.setText(con_func.rs.getString("telefone_fun"));
            txtCel.setText(con_func.rs.getString("celular_fun"));
        }
        catch(Exception erroPesquisa){
            JOptionPane.showMessageDialog(null,"Não foi possivel localizar este funcionario", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JPanel jPanelFoto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JButton lblCaregarFoto;
    private javax.swing.JLabel lblCel;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblEst;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTel;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables

}
