package mr_tooth.financeiro;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import mr_tooth.utilitarios.*;

/**
 *
 * @author pedroh
 */
public class AlteraCheque extends javax.swing.JFrame {
    ConectaBanco con_cheque;
    /** Creates new form AlteraCheque */
    public AlteraCheque(String cod_cheq, String nome_pac, String nome_tit, String vl_cheq, String bc_cheq, String ag_cheq, String ct_cheq, String cp_cheq) {
        initComponents();
        //Inicia a classe ConectaBanco
        con_cheque = new ConectaBanco();
        con_cheque.OpenDB();

        //Inseri nos campos de texto as informações
        txtCodigo.setText(cod_cheq);
        txtPaciente.setText(nome_pac);
        txtTitular.setText(nome_tit);
        txtValor.setText(vl_cheq);
        txtBanco.setText(bc_cheq);
        txtAgencia.setText(ag_cheq);
        txtConta.setText(ct_cheq);
        txtDtCompensacao.setText(cp_cheq);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAgencia = new javax.swing.JTextField();
        lblAgencia = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtBanco = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        lblPaciente = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        lblDtCompensacao = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblTitular = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblBanco = new javax.swing.JLabel();
        txtPaciente = new javax.swing.JTextField();
        txtDtCompensacao = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox();
        lblConta = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alteração Cheque");

        txtAgencia.setEditable(false);

        lblAgencia.setText("Agência :");

        lblCodigo.setText("Código :");

        txtBanco.setEditable(false);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Medical Invoice Flat Stop.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblPaciente.setText("Nome do Paciente :");

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Medical Invoice Flat Check.png"))); // NOI18N
        btnAlterar.setText("Salvar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        lblDtCompensacao.setFont(new java.awt.Font("Segoe UI", 0, 12));
        lblDtCompensacao.setText("Data Compensação :");

        txtCodigo.setEditable(false);

        lblTitular.setText("Nome do Titular :");

        txtTitular.setEditable(false);

        lblValor.setText("Valor :");

        txtValor.setEditable(false);

        lblBanco.setText("Banco :");

        txtPaciente.setEditable(false);

        txtDtCompensacao.setEditable(false);

        lblStatus.setText("Status :");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pendente", "Pago" }));

        lblConta.setText("Conta :");

        txtConta.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDtCompensacao)
                    .addComponent(lblPaciente)
                    .addComponent(lblTitular)
                    .addComponent(lblValor)
                    .addComponent(lblAgencia)
                    .addComponent(lblCodigo)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addComponent(txtTitular, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addComponent(txtPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAgencia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblBanco))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(lblConta)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtConta, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtBanco, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 168, Short.MAX_VALUE)
                            .addComponent(txtDtCompensacao, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                        .addGap(310, 310, 310))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaciente)
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitular)
                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanco)
                    .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgencia)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDtCompensacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtCompensacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnCancelar))
                .addGap(29, 29, 29))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-635)/2, (screenSize.height-460)/2, 635, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try{                       
            String cod_cheq = txtCodigo.getText();
            String nome_pac = txtPaciente.getText();
            String nome_titular = txtTitular.getText();
            String valor = txtValor.getText();
            String banco = txtBanco.getText();
            String agencia = txtAgencia.getText();
            String conta = txtConta.getText();
            String compen = txtDtCompensacao.getText();

            if(nome_titular.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o nome do titular do cheque!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(valor.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o valor do cheque!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(banco.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o nome banco!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(agencia.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o número da agência!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else if(conta.equals("")){
                JOptionPane.showMessageDialog(null,"Por favor, digite o número da conta!","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else{
                //Altera os dados no banco
                String ChequeUpdate = "UPDATE cheques SET nome_pac = '"+nome_pac+"', nometitular_cheq = '"+nome_titular+"', valor_cheq = '"+valor+"'," +
                                        "banco_cheq = '"+banco+"', agencia_cheq = '"+agencia+"', = conta_cheq = '"+conta+"', compensacao_cheq = '"+compen+"'," +
                                        "status_cheq = '"+cbStatus.getSelectedItem()+"' WHERE cod_cheque = "+cod_cheq;
                con_cheque.stmt.executeUpdate(ChequeUpdate);
                JOptionPane.showMessageDialog(null,"Cheque atualizado com sucesso!","Cadastrado!", JOptionPane.INFORMATION_MESSAGE);
            }            
        }
        catch(SQLException erroSQL){
             JOptionPane.showMessageDialog(null,"Não foi possível atualizar os dados do cheque!", "Erro!", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
    * @param args the command line arguments
    */   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblConta;
    private javax.swing.JLabel lblDtCompensacao;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtConta;
    private javax.swing.JTextField txtDtCompensacao;
    private javax.swing.JTextField txtPaciente;
    private javax.swing.JTextField txtTitular;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

}
