package mr_tooth.financeiro;
import javax.swing.JOptionPane;
import mr_tooth.utilitarios.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pedro
 */
public class Cheques extends javax.swing.JFrame {
    ConectaBanco con_cheq;
    /** Creates new form Cheques */
    public Cheques() {
      initComponents();
      con_cheq = new ConectaBanco();
      con_cheq.OpenDB();

      //Mostrando a data atual
      /*DataAgenda dt = new DataAgenda();
      dt.verData();
      String DataAtual = dt.dia+"/"+dt.mes_num+"/"+dt.ano;*/

      //con_cheq.QuerySQL("SELECT * FROM cheques WHERE nometitular_cheq = '"+txtTitular.getText()+"'");
      con_cheq.QuerySQL("SELECT * FROM cheques");
      this.PreencherJtable();
    }

    public void PreencherJtable(){
        DefaultTableModel Modelo = (DefaultTableModel)jTableConsultas.getModel();
        Modelo.setNumRows(0);

        try{
            while(con_cheq.rs.next()){
                Modelo.addRow(new Object [] {
                    con_cheq.rs.getString("cod_cheque"),
                    con_cheq.rs.getString("nome_pac"),
                    con_cheq.rs.getString("nometitular_cheq"),
                    con_cheq.rs.getString("valor_cheq"),
                    con_cheq.rs.getString("banco_cheq"),
                    con_cheq.rs.getString("agencia_cheq"),
                    con_cheq.rs.getString("conta_cheq"),
                    con_cheq.rs.getString("compensacao_cheq"),
                    con_cheq.rs.getString("status_cheq")
                });
            }
        } 
        catch(Exception erroTable){
            JOptionPane.showMessageDialog(null,"Erro ao carregar cheques cadastrados","ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTableConsultas = new javax.swing.JTable();
        lblTitular = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtTitular = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cheques");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("framePacientes"); // NOI18N

        jTableConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Paciente", "Titular", "Valor ", "Banco", "Agencia", "Conta", "Compensação", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(jTableConsultas);
        jTableConsultas.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTableConsultas.getColumnModel().getColumn(1).setPreferredWidth(350);
        jTableConsultas.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTableConsultas.getColumnModel().getColumn(3).setPreferredWidth(120);

        lblTitular.setFont(new java.awt.Font("Segoe UI", 1, 12));
        lblTitular.setText("Nome Titular :");

        btnVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Medical Invoice 3D Search.png"))); // NOI18N
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Medical Invoice 3D Add.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Medical Invoice 3D Edit 2.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mr_tooth/icones/Medical Invoice 3D Delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitular)
                        .addGap(18, 18, 18)
                        .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitular)
                    .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerificar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addGap(41, 41, 41))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-901)/2, (screenSize.height-597)/2, 901, 597);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        new CadastraCheque().setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        con_cheq.QuerySQL("SELECT * FROM cheques WHERE nometitular_cheq = '"+txtTitular.getText()+"'");
        this.PreencherJtable();
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int LinhaSelecionada = this.jTableConsultas.getSelectedRow();
        String CodigoCheque = this.jTableConsultas.getValueAt(LinhaSelecionada, 0).toString();

        try{
            //Busca no banco de dados o código do paciente selecionado para ser excluido
            String ChequeSelecionado = "SELECT * FROM cheques WHERE cod_cheque = "+CodigoCheque;
            con_cheq.QuerySQL(ChequeSelecionado);
            con_cheq.rs.next();

            //Mensagem de confirmação
            String MsgConfirmacao = "Deseja realmente excluir o cheque recebido do paciente: \n "+con_cheq.rs.getString("nome_pac")+" ?";
            int OpcaoEscolhida = JOptionPane.showConfirmDialog(null, MsgConfirmacao, "Excluir", JOptionPane.YES_NO_OPTION);

            if(OpcaoEscolhida == JOptionPane.YES_OPTION){
                //Excluindo a consulta agendada após a confirmação positiva
                String ExcluirConsulta = "DELETE FROM cheques WHERE cod_cheque = "+CodigoCheque;
                int ExcluirSucesso  = con_cheq.stmt.executeUpdate(ExcluirConsulta);

                if(ExcluirSucesso == 1){
                    JOptionPane.showMessageDialog(null,"Cheque excluido com sucesso!","Excluir!", JOptionPane.INFORMATION_MESSAGE);
                    //Atualiza jTable
                    PreencherJtable();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Não foi possível excluir o cheque!", "Erro!", JOptionPane.ERROR_MESSAGE);
                    //Atualiza jTable
                    //PreencherJtable();
                }
            }
            else{
                //Atualiza jTable
                PreencherJtable();
                return;
            }
        }
        catch(Exception erroSQL){
             JOptionPane.showMessageDialog(null,"Erro ao excluir", "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int LinhaSelecionada = this.jTableConsultas.getSelectedRow();
        String cod_cheq  = this.jTableConsultas.getValueAt(LinhaSelecionada, 0).toString();
        String nome_pac  = this.jTableConsultas.getValueAt(LinhaSelecionada, 1).toString();
        String nome_tit  = this.jTableConsultas.getValueAt(LinhaSelecionada, 2).toString();
        String vl_cheq   = this.jTableConsultas.getValueAt(LinhaSelecionada, 3).toString();
        String bc_cheq   = this.jTableConsultas.getValueAt(LinhaSelecionada, 4).toString();
        String ag_cheq   = this.jTableConsultas.getValueAt(LinhaSelecionada, 5).toString();
        String ct_cheq   = this.jTableConsultas.getValueAt(LinhaSelecionada, 6).toString();
        String cp_cheq   = this.jTableConsultas.getValueAt(LinhaSelecionada, 7).toString();
        //String st_cheq   = this.jTableConsultas.getValueAt(LinhaSelecionada, 8).toString();

        con_cheq.CloseDB();

        new AlteraCheque(cod_cheq, nome_pac, nome_tit, vl_cheq, bc_cheq, ag_cheq, ct_cheq, cp_cheq).setVisible(true);
    }//GEN-LAST:event_btnAlterarActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
         public void run(){
                new Cheques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableConsultas;
    private javax.swing.JLabel lblTitular;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables

}
